<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Soal;

class TKPHOTSSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $questions = [
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda adalah kepala divisi di instansi pemerintah. Salah satu staf Anda yang biasanya berkinerja baik tiba-tiba menurun performanya karena masalah keluarga. Anda mengetahui hal ini dari rekan kerjanya. Tindakan apa yang paling mencerminkan integritas dan empati Anda?",
                "opsi_a" => "Memanggil staf tersebut dan memberikan peringatan keras karena performanya menurun tanpa menanyakan penyebabnya",
                "opsi_b" => "Memanggil staf tersebut secara pribadi, menanyakan kondisinya dengan empati, dan menawarkan dukungan atau fleksibilitas kerja sementara",
                "opsi_c" => "Mengabaikan masalah tersebut karena itu adalah urusan pribadi staf dan tidak berpengaruh pada tugas kantor",
                "opsi_d" => "Membicarakan masalah staf tersebut dengan rekan kerja lain untuk mencari solusi tanpa sepengetahuan staf bersangkutan",
                "opsi_e" => "Langsung melaporkan staf tersebut ke atasan karena dianggap tidak profesional dalam bekerja",
                "jawaban_benar" => "B",
                "poin_a" => 2,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 3,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kombinasi sempurna antara integritas (tidak menilai tanpa informasi lengkap), empati (memahami kondisi pribadi), dan kepemimpinan yang proaktif (menawarkan dukungan). Opsi D mendapat 3 poin karena menunjukkan kepedulian tetapi kurang menjaga privasi. Opsi A mendapat 2 poin karena menunjukkan otoritas tetapi kurang empati. Opsi C dan E masing-masing 1 poin karena menunjukkan ketidakpedulian atau tindakan yang tidak proporsional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam rapat koordinasi antar instansi, rekan Anda dari instansi lain menyampaikan data yang menurut Anda tidak akurat. Namun, menyampaikan perbedaan ini di depan umum akan mempermalukan rekan tersebut dan mungkin merusak hubungan kerja. Apa yang akan Anda lakukan?",
                "opsi_a" => "Menyimpan diam diri dan tidak mengoreksi data tersebut untuk menjaga hubungan kerja",
                "opsi_b" => "Mengoreksi data dengan sopan di depan umum dan memberikan penjelasan berbasis data yang objektif",
                "opsi_c" => "Menunggu rapat selesai, lalu menghubungi rekan tersebut secara pribadi untuk membahas perbedaan data",
                "opsi_d" => "Mencatat perbedaan tersebut dan melaporkan ke atasan Anda setelah rapat",
                "opsi_e" => "Menyampaikan perbedaan data dengan nada sinis di depan umum agar rekan tersebut lebih hati-hati",
                "jawaban_benar" => "C",
                "poin_a" => 2,
                "poin_b" => 4,
                "poin_c" => 5,
                "poin_d" => 3,
                "poin_e" => 1,
                "pembahasan" => "Opsi C mendapat 5 poin karena menunjukkan integritas tinggi (tidak mengabaikan kesalahan), empati (menjaga martabat rekan), dan profesionalisme (mengoreksi dengan cara yang tepat). Opsi B mendapat 4 poin karena menunjukkan integritas dan objektivitas tetapi kurang menjaga hubungan interpersonal. Opsi D mendapat 3 poin karena profesional tetapi kurang inisiatif langsung. Opsi A mendapat 2 poin karena menjaga hubungan tetapi mengorbankan integritas. Opsi E mendapat 1 poin karena tidak profesional dan merendahkan orang lain."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda mendapatkan tawaran suap dari kontraktor yang menginginkan proyek tender dimenangkan perusahaannya. Tawaran tersebut cukup besar dan Anda sedang mengalami kesulitan finansial pribadi. Apa tindakan yang paling mencerminkan integritas dan tanggung jawab?",
                "opsi_a" => "Menerima tawaran karena situasi finansial Anda sedang sulit dan berjanji akan membalas budi dengan memenangkan tender",
                "opsi_b" => "Menolak tawaran dengan tegas dan melaporkan kejadian tersebut ke atasan atau unit pengawasan",
                "opsi_c" => "Menolak tawaran tetapi tidak melaporkannya karena khawatir akan konsekuensi pribadi",
                "opsi_d" => "Menerima tawaran tetapi tidak memenangkan tender perusahaan tersebut untuk menjaga 'netralitas'",
                "opsi_e" => "Meminta waktu untuk mempertimbangkan tawaran tersebut sambil mencari informasi lebih lanjut tentang kontraktor",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 4,
                "poin_d" => 1,
                "poin_e" => 2,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan integritas mutlak (menolak korupsi), tanggung jawab (melaporkan pelanggaran), dan ketegasan. Opsi C mendapat 4 poin karena menolak korupsi tetapi kurang tanggung jawab dalam melaporkan. Opsi E mendapat 2 poin karena masih mempertimbangkan tindakan yang salah. Opsi A dan D masing-masing 1 poin karena jelas melanggar integritas dan profesionalisme."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Sebagai pemimpin tim, Anda mengetahui ada konflik antara dua anggota tim yang mengganggu produktivitas. Keduanya adalah staf yang kompeten. Bagaimana cara Anda menyelesaikan konflik ini agar mencerminkan kemampuan kerjasama dan kepemimpinan?",
                "opsi_a" => "Memindahkan salah satu staf ke divisi lain agar konflik berhenti",
                "opsi_b" => "Mediasi konflik dengan mendengarkan kedua belah pihak, mencari akar masalah, dan membangun solusi bersama",
                "opsi_c" => "Mengabaikan konflik dengan asumsi mereka akan menyelesaikan sendiri",
                "opsi_d" => "Memberi peringatan keras kepada keduanya agar tidak mengulangi konflik",
                "opsi_e" => "Mengambil sisi salah satu staf berdasarkan informasi dari pihak ketiga",
                "jawaban_benar" => "B",
                "poin_a" => 2,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kepemimpinan yang matang (mediasi aktif), kemampuan kerjasama (membangun solusi bersama), dan keadilan (mendengarkan kedua pihak). Opsi A dan D masing-masing 2 poin karena menunjukkan otoritas tetapi kurang solusi yang berkelanjutan. Opsi C mendapat 1 poin karena menunjukkan ketidakpedulian. Opsi E mendapat 1 poin karena tidak adil dan tidak objektif."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda ditugaskan untuk membuat kebijakan baru yang akan mempengaruhi banyak pegawai. Kebijakan tersebut akan menimbulkan protes karena mengurangi beberapa fasilitas yang selama ini dinikmati. Bagaimana cara Anda menyikapi situasi ini?",
                "opsi_a" => "Menerapkan kebijakan secara paksa tanpa penjelasan karena itu keputusan atasan",
                "opsi_b" => "Mengadakan forum diskusi dengan pegawai, menjelaskan alasan kebijakan, dan mendengar masukan untuk penyesuaian jika memungkinkan",
                "opsi_c" => "Mengabaikan protes dan tetap menerapkan kebijakan sesuai jadwal",
                "opsi_d" => "Mengundurkan diri dari tugas tersebut karena tidak ingin menangani protes",
                "opsi_e" => "Menunda implementasi kebijakan tanpa batas waktu yang jelas",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 1,
                "poin_e" => 2,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kemampuan komunikasi, empati terhadap pegawai, dan keterbukaan terhadap masukan. Opsi E mendapat 2 poin karena menunjukkan kehati-hatian tetapi kurang keputusan. Opsi A, C, dan D masing-masing 1 poin karena menunjukkan sikap otoriter, ketidakpedulian, atau menghindar dari tanggung jawab."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam situasi darurat di kantor, Anda harus memprioritaskan penyelesaian tugas-tugas penting. Namun, ada staf yang meminta bantuan untuk tugas pribadi yang tidak mendesak. Bagaimana sikap Anda yang mencerminkan orientasi pada pelayanan dan prioritas kerja?",
                "opsi_a" => "Membantu staf tersebut meskipun tugas kantor Anda terbengkalai",
                "opsi_b" => "Menolak dengan sopan dan menjelaskan bahwa Anda sedang menangani situasi darurat, menawarkan bantuan setelah situasi normal",
                "opsi_c" => "Mengabaikan permintaan staf tanpa penjelasan",
                "opsi_d" => "Marah kepada staf tersebut karena tidak peka terhadap situasi",
                "opsi_e" => "Mendelegasikan tugas kantor Anda kepada staf lain agar bisa membantu staf tersebut",
                "jawaban_benar" => "B",
                "poin_a" => 2,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 2,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan orientasi pelayanan (tetap bersedia membantu), profesionalisme (menjelasakan prioritas), dan integritas (tidak mengorbankan tugas utama). Opsi A mendapat 2 poin karena menunjukkan kepedulian tetapi kurang profesionalisme. Opsi C mendapat 2 poin karena profesional tetapi kurang pelayanan. Opsi E mendapat 2 poin karena tidak adil mendelegasikan tugas. Opsi D mendapat 1 poin karena tidak profesional dan emosional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda menemukan kesalahan dalam dokumen kebijakan yang sudah disetujui atasan dan akan segera diterbitkan. Kesalahan tersebut bersifat teknis dan tidak terlalu berdampak besar. Apa yang akan Anda lakukan?",
                "opsi_a" => "Diam saja karena dokumen sudah disetujui atasan dan kesalahan tidak berdampak besar",
                "opsi_b" => "Segera memberitahu atasan tentang kesalahan tersebut dan menyarankan perbaikan sebelum diterbitkan",
                "opsi_c" => "Memperbaiki kesalahan secara diam-diam tanpa memberitahu siapa pun",
                "opsi_d" => "Membicarakan kesalahan tersebut dengan rekan kerja untuk meminta pendapat",
                "opsi_e" => "Menunggu dokumen diterbitkan, lalu mengoreksi dalam edisi berikutnya",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 3,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan integritas tinggi (jujur meskipun dokumen sudah disetujui), tanggung jawab (mencegah kesalahan), dan profesionalisme (komunikasi langsung). Opsi C mendapat 3 poin karena memperbaiki kesalahan tetapi kurang transparansi. Opsi D mendapat 2 poin karena mencari masukan tetapi kurang keputusan. Opsi A dan E masing-masing 1 poin karena menunjukkan ketidakjujuran atau ketidakpedulian."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Sebagai pegawai baru, Anda melihat praktik kerja yang tidak efisien di divisi Anda. Rekan-rekan senior sudah terbiasa dengan cara tersebut. Bagaimana Anda menyampaikan usulan perbaikan?",
                "opsi_a" => "Langsung mengkritik cara kerja senior di depan umum",
                "opsi_b" => "Mengamati dan belajar terlebih dahulu, lalu menyampaikan usulan secara pribadi dengan data dan solusi konkret",
                "opsi_c" => "Mengikuti cara kerja senior tanpa mempertanyakan",
                "opsi_d" => "Melaporkan praktik tersebut ke atasan tanpa berdiskusi dengan rekan",
                "opsi_e" => "Membicarakan keburukan cara kerja senior dengan rekan lain di belakang",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kemampuan adaptasi (belajar terlebih dahulu), komunikasi yang sopan (diskusi pribadi), dan orientasi perbaikan (solusi konkret). Opsi C mendapat 2 poin karena menunjukkan adaptasi tetapi kurang inovasi. Opsi D mendapat 2 poin karena ingin perbaikan tetapi kurang komunikasi langsung. Opsi A dan E masing-masing 1 poin karena tidak sopan dan tidak profesional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda ditawarkan promosi jabatan yang lebih tinggi dengan gaji lebih besar. Namun, promosi tersebut mengharuskan Anda pindah ke daerah yang jauh dari keluarga. Keluarga Anda tidak setuju dengan pindah tersebut. Bagaimana keputusan Anda?",
                "opsi_a" => "Menerima promosi karena karir lebih penting dari keluarga",
                "opsi_b" => "Membahas dengan keluarga, mencari solusi kompromi, dan mempertimbangkan semua aspek sebelum mengambil keputusan",
                "opsi_c" => "Menolak promosi karena tidak ingin berpisah dari keluarga",
                "opsi_d" => "Menerima promosi dan memaksa keluarga untuk ikut pindah",
                "opsi_e" => "Mengundurkan diri dari pekerjaan karena tidak ingin menghadapi dilema",
                "jawaban_benar" => "B",
                "poin_a" => 2,
                "poin_b" => 5,
                "poin_c" => 3,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kemampuan pengambilan keputusan yang matang (mempertimbangkan semua aspek), komunikasi keluarga, dan keseimbangan hidup kerja. Opsi C mendapat 3 poin karena menunjukkan kepedulian keluarga tetapi kurang fleksibilitas. Opsi A mendapat 2 poin karena orientasi karir tetapi kurang keseimbangan. Opsi D dan E masing-masing 1 poin karena egois atau menghindar."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam rapat evaluasi kinerja, atasan Anda memberikan kritik yang menurut Anda tidak adil karena tidak mempertimbangkan kondisi kerja yang sulit. Bagaimana sikap Anda yang mencerminkan profesionalisme dan kontrol emosi?",
                "opsi_a" => "Menyampaikan ketidaksetujuan dengan emosi di depan umum",
                "opsi_b" => "Mendengarkan dengan tenang, mencatat poin-poin kritik, lalu menyampaikan klarifikasi dengan data dan fakta secara profesional",
                "opsi_c" => "Diam saja dan menerima kritik tanpa pembelaan",
                "opsi_d" => "Menyimpan kekecewaan dan mengeluh kepada rekan kerja setelah rapat",
                "opsi_e" => "Mengancam akan mengundurkan diri jika kritik tidak ditarik kembali",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kontrol emosi (tenang), profesionalisme (menggunakan data), dan komunikasi yang konstruktif. Opsi C mendapat 2 poin karena sabar tetapi kurang pembelaan diri. Opsi D mendapat 2 poin karena tidak eksplosif tetapi kurang profesional. Opsi A dan E masing-masing 1 poin karena emosional dan tidak profesional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda mengetahui bahwa rekan kerja Anda melakukan pelanggaran disiplin ringan yang tidak diketahui atasan. Pelanggaran tersebut tidak berdampak besar pada kinerja. Apa tindakan Anda?",
                "opsi_a" => "Melaporkan rekan tersebut ke atasan untuk menegakkan disiplin",
                "opsi_b" => "Menasihati rekan tersebut secara pribadi agar tidak mengulangi pelanggaran",
                "opsi_c" => "Mengabaikan karena pelanggaran ringan dan tidak berdampak",
                "opsi_d" => "Membicarakan pelanggaran tersebut dengan rekan lain",
                "opsi_e" => "Memanfaatkan informasi tersebut untuk meminta keuntungan dari rekan tersebut",
                "jawaban_benar" => "B",
                "poin_a" => 3,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan empati (menasihati bukan melapor), integritas (tidak memanfaatkan situasi), dan pendekatan yang manusiawi. Opsi A mendapat 3 poin karena menegakkan disiplin tetapi kurang pendekatan edukatif. Opsi C mendapat 2 poin karena toleran tetapi kurang ketegasan. Opsi D mendapat 2 poin karena kurang profesional. Opsi E mendapat 1 poin karena tidak bermoral."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda sedang mengerjakan tugas penting dengan deadline ketat. Tiba-tiba, ada rekan yang meminta bantuan untuk tugasnya yang juga mendesak. Bagaimana Anda menangani situasi ini?",
                "opsi_a" => "Menolak karena fokus pada tugas Anda sendiri",
                "opsi_b" => "Membantu sebisa mungkin tanpa mengorbankan deadline tugas Anda",
                "opsi_c" => "Menerima semua permintaan bantuan rekan tersebut meskipun tugas Anda terbengalai",
                "opsi_d" => "Menyarankan rekan tersebut mencari bantuan dari orang lain",
                "opsi_e" => "Marah karena rekan tidak peka terhadap deadline Anda",
                "jawaban_benar" => "B",
                "poin_a" => 2,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 3,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan orientasi kerjasama (membantu), profesionalisme (menjaga deadline), dan keseimbangan prioritas. Opsi D mendapat 3 poin karena menunjukkan inisiatif solusi alternatif. Opsi A dan C masing-masing 2 poin karena kurang kerjasama atau kurang profesional. Opsi E mendapat 1 poin karena emosional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam forum diskusi publik, ada peserta yang mengeluarkan pendapat yang bertentangan dengan pandangan Anda. Pendapat tersebut disetujui banyak peserta lain. Bagaimana sikap Anda?",
                "opsi_a" => "Menyerang pendapat tersebut dengan keras karena menurut Anda salah",
                "opsi_b" => "Menghargai perbedaan pendapat, menyampaikan pandangan Anda dengan data dan argumen yang objektif",
                "opsi_c" => "Diam saja dan mengikuti pendapat mayoritas",
                "opsi_d" => "Meninggalkan forum karena tidak setuju dengan pendapat mayoritas",
                "opsi_e" => "Menertawarkan peserta tersebut karena dianggap tidak kompeten",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan toleransi (menghargai perbedaan), integritas (tetap pada pendapat), dan komunikasi yang konstruktif. Opsi C mendapat 2 poin karena adaptif tetapi kurang keberanian. Opsi D mendapat 2 poin karena menjaga integritas tetapi kurang toleransi. Opsi A dan E masing-masing 1 poin karena intoleran dan tidak sopan."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda ditugaskan mengawasi proyek yang melibatkan banyak pihak. Salah satu pihak mencoba menyuap Anda agar memberikan rekomendasi yang menguntungkan mereka. Bagaimana tindakan Anda?",
                "opsi_a" => "Menerima suap karena semua orang juga melakukannya",
                "opsi_b" => "Menolak suap dengan tegas dan melaporkan kejadian tersebut ke pihak berwenang",
                "opsi_c" => "Menolak suap tetapi tidak melaporkan karena khawatir konsekuensi",
                "opsi_d" => "Meminta suap dalam jumlah yang lebih besar",
                "opsi_e" => "Menerima suap tetapi tetap memberikan rekomendasi yang objektif",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 4,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan integritas mutlak (anti-korupsi), tanggung jawab (melaporkan), dan ketegasan. Opsi C mendapat 4 poin karena menolak korupsi tetapi kurang tanggung jawab. Opsi A, D, dan E masing-masing 1 poin karena jelas melanggar integritas."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Sebagai pemimpin, Anda harus membagikan tugas-tugas penting kepada tim. Ada anggota tim yang baru bergabung dan belum berpengalaman. Bagaimana Anda membagikan tugas?",
                "opsi_a" => "Memberikan tugas paling mudah kepada anggota baru karena belum berpengalaman",
                "opsi_b" => "Memberikan tugas yang sesuai dengan kemampuan, memberikan pendampingan untuk anggota baru, dan memberikan kesempatan berkembang",
                "opsi_c" => "Memberikan tugas paling sulit untuk menguji kemampuan anggota baru",
                "opsi_d" => "Tidak memberikan tugas kepada anggota baru karena belum siap",
                "opsi_e" => "Memberikan tugas secara acak tanpa mempertimbangkan kemampuan",
                "jawaban_benar" => "B",
                "poin_a" => 2,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kepemimpinan yang adil (sesuai kemampuan), orientasi pengembangan (pendampingan), dan kepercayaan. Opsi A dan C masing-masing 2 poin karena kurang adil atau terlalu berisiko. Opsi D mendapat 1 poin karena tidak memberi kesempatan. Opsi E mendapat 1 poin karena tidak profesional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda mendapatkan informasi bahwa atasan Anda akan melakukan tindakan yang melanggar regulasi. Informasi tersebut belum terkonfirmasi. Apa tindakan Anda?",
                "opsi_a" => "Menyebarkan informasi tersebut ke rekan kerja lain",
                "opsi_b" => "Mengkonfirmasi informasi tersebut dengan atasan secara pribadi dan mencari klarifikasi",
                "opsi_c" => "Melaporkan langsung ke atasan atasan tanpa konfirmasi",
                "opsi_d" => "Diam saja dan mengabaikan informasi tersebut",
                "opsi_e" => "Mencatat informasi tersebut untuk digunakan jika terjadi masalah",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan integritas (tidak menyebarkan gosip), profesionalisme (konfirmasi langsung), dan komunikasi yang baik. Opsi C mendapat 2 poin karena ingin menegakkan regulasi tetapi kurang konfirmasi. Opsi D mendapat 2 poin karena hati-hati tetapi kurang tanggung jawab. Opsi A dan E masing-masing 1 poin karena tidak profesional atau manipulatif."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam bekerja, Anda sering mendapatkan tugas tambahan di luar job description. Tugas tersebut menambah beban kerja Anda tetapi tidak ada kompensasi tambahan. Bagaimana sikap Anda?",
                "opsi_a" => "Menolak semua tugas tambahan karena di luar tanggung jawab",
                "opsi_b" => "Menerima tugas tambahan sebagai kesempatan belajar dan berkontribusi lebih banyak",
                "opsi_c" => "Menerima tetapi selalu mengeluh tentang beban kerja",
                "opsi_d" => "Menerima tetapi mengerjakan dengan kualitas rendah",
                "opsi_e" => "Meminta kompensasi tambahan sebelum menerima tugas",
                "jawaban_benar" => "B",
                "poin_a" => 2,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 3,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan orientasi pelayanan (siap membantu), inisiatif (kesempatan belajar), dan sikap positif. Opsi E mendapat 3 poin karena realistis tetapi kurang orientasi pelayanan. Opsi A mendapat 2 poin karena menegakkan batasan tetapi kurang fleksibel. Opsi C mendapat 2 poin karena menerima tetapi negatif. Opsi D mendapat 1 poin karena tidak profesional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda sedang mengikuti pelatihan yang penting untuk pengembangan karir. Di hari terakhir pelatihan, ada masalah mendesak di kantor yang membutuhkan kehadiran Anda. Apa yang akan Anda lakukan?",
                "opsi_a" => "Tidak menghadiri pelatihan hari terakhir karena tugas kantor lebih penting",
                "opsi_b" => "Mengkomunikasikan dengan atasan, mencari solusi alternatif, dan tetap berusaha menyelesaikan pelatihan",
                "opsi_c" => "Mengabaikan masalah kantor dan fokus menyelesaikan pelatihan",
                "opsi_d" => "Mengundurkan diri dari pelatihan karena konflik dengan tugas kantor",
                "opsi_e" => "Minta rekan untuk menggantikan Anda di kantor tanpa memberitahu atasan",
                "jawaban_benar" => "B",
                "poin_a" => 2,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kemampuan manajemen konflik, komunikasi yang baik, dan komitmen terhadap keduanya. Opsi A, C, dan D masing-masing 2 poin karena kurang solusi yang komprehensif. Opsi E mendapat 1 poin karena tidak profesional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda menemukan kesalahan dalam pekerjaan yang sudah diselesaikan oleh rekan kerja dan sudah disubmit ke klien. Kesalahan tersebut bisa diperbaiki dengan revisi kecil. Apa tindakan Anda?",
                "opsi_a" => "Diam saja karena sudah disubmit dan kesalahan kecil",
                "opsi_b" => "Segera memberitahu rekan tersebut dan membantu memperbaiki kesalahan sebelum klien mengetahui",
                "opsi_c" => "Memperbaiki sendiri tanpa memberitahu rekan tersebut",
                "opsi_d" => "Melaporkan ke atasan bahwa rekan tersebut membuat kesalahan",
                "opsi_e" => "Menunggu klien menemukan kesalahan baru bertindak",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 3,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kerjasama (membantu rekan), integritas (jujur), dan profesionalisme (preventif). Opsi C mendapat 3 poin karena memperbaiki tetapi kurang komunikasi. Opsi D mendapat 2 poin karena ingin kebenaran tetapi kurang kerjasama. Opsi A dan E masing-masing 1 poin karena tidak bertanggung jawab."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda adalah anggota tim yang sedang mengerjakan proyek penting dengan deadline ketat. Salah satu anggota tim tidak dapat menyelesaikan bagiannya karena sakit. Bagaimana sikap Anda yang mencerminkan orientasi kerjasama?",
                "opsi_a" => "Mengabaikan dan tetap fokus pada bagian Anda sendiri",
                "opsi_b" => "Menawarkan bantuan untuk menyelesaikan bagian rekan tersebut tanpa mengorbankan deadline Anda",
                "opsi_c" => "Melaporkan ke atasan bahwa rekan tersebut tidak bekerja",
                "opsi_d" => "Mencela rekan tersebut di depan tim lain",
                "opsi_e" => "Menunggu atasan menyelesaikan masalah",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 1,
                "poin_e" => 2,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kerjasama proaktif, empati, dan orientasi tim. Opsi E mendapat 2 poin karena menunggu tetapi kurang inisiatif. Opsi A, C, dan D masing-masing 1 poin karena tidak menunjukkan kerjasama atau tidak profesional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam rapat koordinasi, ada rekan yang mengeluarkan ide yang menurut Anda kurang tepat. Namun, rekan tersebut adalah orang yang sensitif dan mudah tersinggung. Bagaimana cara Anda menyampaikan kritik?",
                "opsi_a" => "Menertawakan ide tersebut di depan umum",
                "opsi_b" => "Menyampaikan kritik secara pribadi dengan bahasa yang membangun dan memberikan solusi alternatif",
                "opsi_c" => "Diam saja dan menerima ide tersebut",
                "opsi_d" => "Mengeluh kepada rekan lain tentang ide tersebut",
                "opsi_e" => "Menolak ide dengan keras di depan umum",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kemampuan komunikasi yang baik, empati, dan pendekatan yang membangun. Opsi C mendapat 2 poin karena menghindari konflik tetapi kurang konstruktif. Opsi A, D, dan E masing-masing 1 poin karena tidak sopan atau tidak profesional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda mendapatkan tugas baru yang tidak sesuai dengan keahlian Anda. Namun, tugas tersebut penting untuk organisasi. Bagaimana sikap Anda?",
                "opsi_a" => "Menolak tugas karena tidak sesuai keahlian",
                "opsi_b" => "Menerima tugas dengan semangat belajar dan meminta pendampingan jika diperlukan",
                "opsi_c" => "Menerima tetapi mengerjakan dengan asal-asalan",
                "opsi_d" => "Mendelegasikan tugas kepada orang lain tanpa izin",
                "opsi_e" => "Mengeluh tentang tugas tersebut kepada rekan",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan sikap adaptif, orientasi pembelajaran, dan tanggung jawab. Opsi A, C, D, dan E masing-masing 1 poin karena menunjukkan ketidakmauan, ketidakprofesionalan, atau sikap negatif."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda mengetahui bahwa atasan Anda akan melakukan perjalanan dinas dengan menggunakan dana yang tidak sesuai peraturan. Apa tindakan Anda?",
                "opsi_a" => "Diam saja karena itu urusan atasan",
                "opsi_b" => "Mengingatkan atasan secara pribadi tentang peraturan dan risikonya",
                "opsi_c" => "Melaporkan langsung ke unit pengawasan",
                "opsi_d" => "Menyebarkan informasi tersebut ke rekan kerja",
                "opsi_e" => "Ikut serta dalam perjalanan dinas tersebut",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 3,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan integritas, keberanian, dan pendekatan yang bijaksana. Opsi C mendapat 3 poin karena menegakkan regulasi tetapi kurang pendekatan interpersonal. Opsi A, D, dan E masing-masing 1 poin karena tidak bertanggung jawab atau melanggar integritas."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam situasi krisis, Anda harus mengambil keputusan cepat. Informasi yang tersedia tidak lengkap. Bagaimana cara Anda mengambil keputusan?",
                "opsi_a" => "Menunggu informasi lengkap sebelum mengambil keputusan",
                "opsi_b" => "Mengambil keputusan berdasarkan informasi yang tersedia dengan pertimbangan risiko",
                "opsi_c" => "Mendelegasikan keputusan kepada orang lain",
                "opsi_d" => "Mengambil keputusan tanpa pertimbangan apapun",
                "opsi_e" => "Menghindari mengambil keputusan",
                "jawaban_benar" => "B",
                "poin_a" => 2,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kemampuan pengambilan keputusan yang matang, analisis risiko, dan tanggung jawab. Opsi A dan C masing-masing 2 poin karena hati-hati tetapi kurang inisiatif. Opsi D dan E masing-masing 1 poin karena ceroboh atau menghindar."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda diminta menjadi pembicara dalam acara resmi instansi. Namun, Anda merasa kurang percaya diri berbicara di depan umum. Bagaimana sikap Anda?",
                "opsi_a" => "Menolak tugas karena tidak percaya diri",
                "opsi_b" => "Menerima tugas dan mempersiapkan diri dengan baik untuk meningkatkan kepercayaan diri",
                "opsi_c" => "Menerima tetapi meminta orang lain menggantikan",
                "opsi_d" => "Menerima tetapi tidak mempersiapkan diri",
                "opsi_e" => "Mengeluh kepada atasan tentang tugas tersebut",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan sikap positif, inisiatif pengembangan diri, dan tanggung jawab. Opsi C mendapat 2 poin karena menerima tetapi kurang komitmen. Opsi A, D, dan E masing-masing 1 poin karena menolak, tidak profesional, atau negatif."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Rekan kerja Anda sering terlambat datang ke kantor yang mengganggu produktivitas tim. Bagaimana cara Anda menangani situasi ini?",
                "opsi_a" => "Melaporkan langsung ke atasan",
                "opsi_b" => "Mengajak bicara rekan tersebut secara pribadi untuk memahami masalah dan mencari solusi",
                "opsi_c" => "Mengabaikan karena itu urusan pribadi",
                "opsi_d" => "Mencela rekan tersebut di depan tim lain",
                "opsi_e" => "Meniru perilaku rekan tersebut",
                "jawaban_benar" => "B",
                "poin_a" => 2,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan pendekatan yang manusiawi, empati, dan orientasi solusi. Opsi A mendapat 2 poin karena menegakkan disiplin tetapi kurang pendekatan edukatif. Opsi C, D, dan E masing-masing 1 poin karena tidak peduli, tidak profesional, atau mengikuti perilaku negatif."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda mendapatkan promosi jabatan yang membuat Anda menjadi atasan dari rekan-rekan kerja yang dulu selevel. Bagaimana cara Anda membangun hubungan kerja yang baik?",
                "opsi_a" => "Menunjukkan otoritas dan memisahkan diri dari rekan kerja",
                "opsi_b" => "Mempertahankan hubungan baik dengan pendekatan yang profesional dan adil",
                "opsi_c" => "Memberikan keistimewaan kepada rekan kerja yang dulu dekat",
                "opsi_d" => "Mengubah sikap menjadi dingin dan formal",
                "opsi_e" => "Menghindari interaksi dengan rekan kerja lama",
                "jawaban_benar" => "B",
                "poin_a" => 2,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kemampuan adaptasi, profesionalisme, dan kepemimpinan yang adil. Opsi A dan D masing-masing 2 poin karena menunjukkan otoritas tetapi kurang hubungan interpersonal. Opsi C mendapat 1 poin karena tidak adil. Opsi E mendapat 1 poin karena menghindar."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam menghadapi perubahan organisasi yang besar, banyak pegawai merasa cemas dan resisten. Bagaimana sikap Anda yang mencerminkan adaptabilitas?",
                "opsi_a" => "Menolak perubahan dan bergabung dengan pegawai yang resisten",
                "opsi_b" => "Menerima perubahan dengan positif, mempelajari hal baru, dan membantu rekan beradaptasi",
                "opsi_c" => "Diam saja dan menunggu instruksi",
                "opsi_d" => "Mengeluh tentang perubahan tersebut",
                "opsi_e" => "Mencari pekerjaan lain karena tidak setuju perubahan",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan adaptabilitas tinggi, sikap positif, dan orientasi membantu. Opsi C mendapat 2 poin karena pasif tetapi tidak resisten. Opsi A, D, dan E masing-masing 1 poin karena resisten, negatif, atau menghindar."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda menemukan bahwa sistem kerja di instansi Anda tidak efisien dan membuang banyak waktu. Namun, mengubah sistem membutuhkan persetujuan banyak pihak. Bagaimana tindakan Anda?",
                "opsi_a" => "Mengabaikan dan mengikuti sistem yang ada",
                "opsi_b" => "Mengumpulkan data, menyusun proposal perbaikan, dan menyampaikan melalui kanal yang tepat",
                "opsi_c" => "Mengeluh tentang sistem kepada rekan kerja",
                "opsi_d" => "Mengubah sistem sendiri tanpa persetujuan",
                "opsi_e" => "Menunggu orang lain yang mengusulkan perubahan",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 1,
                "poin_e" => 2,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan inisiatif, analisis sistematis, dan pendekatan yang profesional. Opsi E mendapat 2 poin karena menunggu tetapi kurang inisiatif. Opsi A, C, dan D masing-masing 1 poin karena pasif, negatif, atau tidak mengikuti prosedur."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam situasi konflik antar divisi, Anda diminta mengambil sisi salah satu divisi oleh atasan Anda. Namun, Anda menilai divisi lain juga memiliki alasan yang valid. Bagaimana sikap Anda?",
                "opsi_a" => "Mengikuti perintah atasan tanpa mempertanyakan",
                "opsi_b" => "Menyampaikan pandangan objektif kepada atasan dengan data dari kedua belah pihak",
                "opsi_c" => "Menolak untuk terlibat dalam konflik",
                "opsi_d" => "Mengambil sisi divisi yang lebih berkuasa",
                "opsi_e" => "Membocorkan informasi ke divisi lain",
                "jawaban_benar" => "B",
                "poin_a" => 2,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan integritas, objektivitas, dan keberanian menyampaikan kebenaran. Opsi A mendapat 2 poin karena taat tetapi kurang kritis. Opsi C, D, dan E masing-masing 1 poin karena menghindar, tidak adil, atau melanggar integritas."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda mendapatkan tugas yang membutuhkan kerjasama dengan divisi lain yang dikenal sulit diajak kerjasama. Bagaimana cara Anda membangun kerjasama?",
                "opsi_a" => "Menghindari kerjasama dengan divisi tersebut",
                "opsi_b" => "Menghubungi pihak terkait, menjelaskan tujuan, dan mencari titik temu untuk kerjasama",
                "opsi_c" => "Melaporkan ke atasan bahwa divisi tersebut sulit diajak kerjasama",
                "opsi_d" => "Memaksa divisi tersebut untuk bekerja sama",
                "opsi_e" => "Menunggu divisi tersebut menginisiasi kerjasama",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kemampuan negosiasi, inisiatif, dan orientasi kerjasama. Opsi C mendapat 2 poin karena melaporkan tetapi kurang inisiatif langsung. Opsi A, D, dan E masing-masing 1 poin karena menghindar, memaksa, atau pasif."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam evaluasi kinerja tahunan, Anda mendapatkan penilaian yang menurut Anda tidak adil. Bagaimana cara Anda menyikapi hal ini?",
                "opsi_a" => "Menerima penilaian tanpa pembelaan",
                "opsi_b" => "Meminta klarifikasi secara profesional dengan data dan bukti kinerja Anda",
                "opsi_c" => "Marah dan mengancam akan mengundurkan diri",
                "opsi_d" => "Mengeluh kepada rekan kerja",
                "opsi_e" => "Mencari cara untuk menyuap penilai",
                "jawaban_benar" => "B",
                "poin_a" => 2,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan profesionalisme, kemampuan komunikasi, dan keberanian membela diri dengan cara yang tepat. Opsi A mendapat 2 poin karena sabar tetapi kurang pembelaan diri. Opsi C, D, dan E masing-masing 1 poin karena emosional, tidak profesional, atau melanggar integritas."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda diminta untuk mengawasi kerja rekan yang lebih senior dan berpengalaman. Rekan tersebut tidak nyaman dengan pengawasan Anda. Bagaimana cara Anda menjalin hubungan kerja?",
                "opsi_a" => "Menunjukkan otoritas tanpa mempertimbangkan perasaan rekan",
                "opsi_b" => "Menyampaikan bahwa pengawasan adalah prosedur dan menawarkan pendekatan kolaboratif",
                "opsi_c" => "Menghindari mengawasi untuk menjaga hubungan baik",
                "opsi_d" => "Melaporkan rekan tersebut ke atasan",
                "opsi_e" => "Mendelegasikan pengawasan kepada orang lain",
                "jawaban_benar" => "B",
                "poin_a" => 2,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kemampuan komunikasi, empati, dan profesionalisme. Opsi A dan D masing-masing 2 poin karena otoriter tetapi menjalankan tugas. Opsi C mendapat 1 poin karena tidak menjalankan tugas. Opsi E mendapat 1 poin karena mendelegasikan tanpa alasan."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam situasi darurat, Anda harus mengambil keputusan yang akan mempengaruhi banyak orang. Namun, Anda tidak memiliki otoritas penuh. Bagaimana tindakan Anda?",
                "opsi_a" => "Menunggu otoritas penuh sebelum bertindak",
                "opsi_b" => "Mengambil keputusan yang diperlukan untuk keselamatan dan melaporkan kemudian",
                "opsi_c" => "Menghindari mengambil keputusan apapun",
                "opsi_d" => "Mengambil keputusan tanpa pertimbangan",
                "opsi_e" => "Mencari orang lain yang bertanggung jawab",
                "jawaban_benar" => "B",
                "poin_a" => 2,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 1,
                "poin_e" => 2,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan tanggung jawab, keberanian, dan prioritas keselamatan. Opsi A dan E masing-masing 2 poin karena mengikuti prosedur tetapi kurang responsif. Opsi C dan D masing-masing 1 poin karena tidak bertindak atau ceroboh."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda mengetahui bahwa rekan kerja Anda memiliki masalah kesehatan yang mempengaruhi kinerjanya tetapi tidak mau mengakuinya. Bagaimana tindakan Anda?",
                "opsi_a" => "Mengabaikan karena itu urusan pribadi",
                "opsi_b" => "Mengajak bicara secara pribadi dengan empati dan menawarkan bantuan",
                "opsi_c" => "Melaporkan ke atasan",
                "opsi_d" => "Membicarakan masalah tersebut dengan rekan lain",
                "opsi_e" => "Menekan rekan tersebut untuk mengaku",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan empati, pendekatan manusiawi, dan kepedulian. Opsi C mendapat 2 poin karena ingin membantu tetapi kurang pendekatan personal. Opsi A, D, dan E masing-masing 1 poin karena tidak peduli, tidak profesional, atau memaksa."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam rapat, ide Anda dikritik keras oleh atasan di depan rekan kerja lain. Bagaimana sikap Anda yang mencerminkan profesionalisme?",
                "opsi_a" => "Menyampaikan ketidaksetujuan dengan emosi",
                "opsi_b" => "Menerima kritik dengan tenang, mencatat poin-poin, dan mengklarifikasi secara objektif",
                "opsi_c" => "Diam saja dan merasa tersinggung",
                "opsi_d" => "Mengundurkan diri dari rapat",
                "opsi_e" => "Mengeluh kepada rekan kerja setelah rapat",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kontrol emosi, profesionalisme, dan sikap konstruktif. Opsi C mendapat 2 poin karena sabar tetapi kurang pembelaan diri. Opsi A, D, dan E masing-masing 1 poin karena emosional, tidak profesional, atau negatif."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda mendapatkan tugas yang membutuhkan kreativitas tinggi tetapi Anda merasa tidak cukup kreatif. Bagaimana cara Anda menghadapi tantangan ini?",
                "opsi_a" => "Menolak tugas karena tidak kreatif",
                "opsi_b" => "Menerima tugas, melakukan riset, berdiskusi dengan rekan, dan mengembangkan ide",
                "opsi_c" => "Mengerjakan dengan cara standar tanpa inovasi",
                "opsi_d" => "Mendelegasikan kepada orang yang lebih kreatif",
                "opsi_e" => "Menunggu inspirasi datang tanpa usaha",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan inisiatif, kolaborasi, dan orientasi pengembangan. Opsi C dan D masing-masing 2 poin karena menerima tetapi kurang inovasi atau realistis. Opsi A dan E masing-masing 1 poin karena menolak atau pasif."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam situasi di mana Anda harus memprioritaskan antara kualitas dan kecepatan, bagaimana keputusan Anda?",
                "opsi_a" => "Mengorbankan kualitas demi kecepatan",
                "opsi_b" => "Menyeimbangkan keduanya dengan komunikasi dan manajemen prioritas yang baik",
                "opsi_c" => "Mengorbankan kecepatan demi kualitas sempurna",
                "opsi_d" => "Mengikuti instruksi tanpa berpikir",
                "opsi_e" => "Menghindar mengambil keputusan",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kemampuan manajemen, komunikasi, dan keseimbangan. Opsi C mendapat 2 poin karena mengutamakan kualitas tetapi kurang fleksibel. Opsi A, D, dan E masing-masing 1 poin karena tidak seimbang, pasif, atau menghindar."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda mengetahui bahwa ada pegawai yang melakukan kebocoran informasi ke media. Namun, Anda tidak yakin siapa pelakunya. Bagaimana tindakan Anda?",
                "opsi_a" => "Menuduh pegawai yang mencurigakan tanpa bukti",
                "opsi_b" => "Melaporkan ke atasan dengan informasi yang ada dan menyarankan investigasi",
                "opsi_c" => "Diam saja dan mengabaikan",
                "opsi_d" => "Menyebarkan gosip ke rekan kerja",
                "opsi_e" => "Menginvestigasi sendiri tanpa wewenang",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 1,
                "poin_e" => 2,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan integritas, tanggung jawab, dan mengikuti prosedur. Opsi E mendapat 2 poin karena inisiatif tetapi kurang wewenang. Opsi A, C, dan D masing-masing 1 poin karena tidak adil, tidak peduli, atau tidak profesional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam menghadapi perubahan kepemimpinan di instansi, bagaimana sikap Anda untuk mendukung transisi yang baik?",
                "opsi_a" => "Meresistensi perubahan kepemimpinan",
                "opsi_b" => "Mendukung transisi dengan terbuka, memberikan kesempatan kepada pemimpin baru",
                "opsi_c" => "Mengabaikan perubahan dan tetap bekerja seperti biasa",
                "opsi_d" => "Mengeluh tentang pemimpin lama",
                "opsi_e" => "Mencari cara untuk memanipulasi situasi",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan adaptabilitas, sikap positif, dan profesionalisme. Opsi C mendapat 2 poin karena stabil tetapi kurang dukungan aktif. Opsi A, D, dan E masing-masing 1 poin karena resisten, negatif, atau manipulatif."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda diminta untuk melakukan tugas yang bertentangan dengan nilai-nilai pribadi Anda. Namun, tugas tersebut legal dan sesuai prosedur. Bagaimana keputusan Anda?",
                "opsi_a" => "Menolak tugas karena bertentangan dengan nilai pribadi",
                "opsi_b" => "Mencoba memahami konteks, mendiskusikan dengan atasan, dan mencari solusi kompromi",
                "opsi_c" => "Melaksanakan tugas tetapi dengan rasa tidak nyaman",
                "opsi_d" => "Mendelegasikan kepada orang lain",
                "opsi_e" => "Mengeluh tentang tugas tersebut",
                "jawaban_benar" => "B",
                "poin_a" => 2,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan keterbukaan, kemampuan dialog, dan keseimbangan nilai-nilai. Opsi A dan C masing-masing 2 poin karena menjaga nilai tetapi kurang fleksibel atau tidak nyaman. Opsi D dan E masing-masing 1 poin karena menghindar atau negatif."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam situasi di mana Anda harus memberikan feedback negatif kepada rekan kerja, bagaimana cara Anda melakukannya?",
                "opsi_a" => "Menyampaikan dengan keras di depan umum",
                "opsi_b" => "Menyampaikan secara pribadi, spesifik, dan dengan fokus pada perbaikan",
                "opsi_c" => "Menghindari memberikan feedback",
                "opsi_d" => "Menyampaikan secara tidak langsung",
                "opsi_e" => "Menyampaikan melalui orang lain",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kemampuan komunikasi, empati, dan orientasi perbaikan. Opsi D mendapat 2 poin karena memberi feedback tetapi kurang langsung. Opsi A, C, dan E masing-masing 1 poin karena kasar, menghindar, atau tidak profesional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda mendapatkan kesempatan untuk promosi yang membutuhkan pindah ke lokasi yang tidak Anda sukai. Bagaimana keputusan Anda?",
                "opsi_a" => "Menolak promosi karena tidak suka lokasinya",
                "opsi_b" => "Mempertimbangkan semua aspek, mendiskusikan dengan keluarga, dan mengambil keputusan matang",
                "opsi_c" => "Menerima tanpa berpikir",
                "opsi_d" => "Meminta kompensasi lebih tinggi di instansi saat ini",
                "opsi_e" => "Mengundurkan diri karena tidak ingin menghadapi pilihan sulit",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan pengambilan keputusan yang matang, komunikasi, dan keseimbangan. Opsi C mendapat 2 poin karena menerima tetapi kurang pertimbangan. Opsi A, D, dan E masing-masing 1 poin karena tidak fleksibel, manipulatif, atau menghindar."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam menghadapi rekan kerja yang selalu pesimis dan negatif, bagaimana cara Anda mempengaruhi sikapnya?",
                "opsi_a" => "Ikut menjadi pesimis dan negatif",
                "opsi_b" => "Menjadi teladan positif, memberikan dukungan, dan membantu melihat sisi baik",
                "opsi_c" => "Menghindari rekan tersebut",
                "opsi_d" => "Mencela rekan tersebut di depan umum",
                "opsi_e" => "Melaporkan rekan tersebut ke atasan",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 1,
                "poin_e" => 2,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan sikap positif, empati, dan kemampuan mempengaruhi. Opsi E mendapat 2 poin karena melaporkan tetapi kurang pendekatan langsung. Opsi A, C, dan D masing-masing 1 poin karena negatif, menghindar, atau tidak profesional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda mengetahui bahwa ada pegawai yang melakukan pelanggaran ringan tetapi berulang. Bagaimana cara Anda menangani situasi ini?",
                "opsi_a" => "Mengabaikan karena pelanggaran ringan",
                "opsi_b" => "Mengajak bicara, mencari akar masalah, dan membantu mencari solusi",
                "opsi_c" => "Melaporkan langsung tanpa pendekatan",
                "opsi_d" => "Memberikan hukuman tanpa dialog",
                "opsi_e" => "Mencela pegawai tersebut di depan umum",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan pendekatan edukatif, empati, dan orientasi solusi. Opsi C mendapat 2 poin karena menegakkan disiplin tetapi kurang pendekatan. Opsi A, D, dan E masing-masing 1 poin karena tidak peduli, keras, atau tidak profesional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam situasi di mana Anda harus bekerja dengan tim yang memiliki kompetensi berbeda-beda, bagaimana cara Anda memaksimalkan potensi tim?",
                "opsi_a" => "Memaksakan standar yang sama kepada semua",
                "opsi_b" => "Mengenali kekuatan masing-masing, membagikan tugas sesuai kompetensi, dan memberikan pendampingan",
                "opsi_c" => "Mengerjakan sendiri semua tugas penting",
                "opsi_d" => "Mengabaikan perbedaan kompetensi",
                "opsi_e" => "Mendelegasikan semua tugas kepada yang paling kompeten",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kepemimpinan yang bijaksana, kemampuan manajemen talenta, dan orientasi pengembangan. Opsi C mendapat 2 poin karena bertanggung jawab tetapi kurang delegasi. Opsi A, D, dan E masing-masing 1 poin karena tidak adil, tidak peduli, atau tidak efektif."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda mendapatkan tugas yang membutuhkan kerjasama dengan pihak eksternal yang sulit diajak komunikasi. Bagaimana cara Anda membangun komunikasi?",
                "opsi_a" => "Menghindari komunikasi dengan pihak eksternal",
                "opsi_b" => "Mencari titik temu, menggunakan bahasa yang mudah dipahami, dan membangun kepercayaan",
                "opsi_c" => "Memaksa pihak eksternal mengikuti cara Anda",
                "opsi_d" => "Melaporkan kesulitan ke atasan",
                "opsi_e" => "Mendelegasikan komunikasi kepada orang lain",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kemampuan komunikasi, adaptabilitas, dan orientasi kerjasama. Opsi D mendapat 2 poin karena melaporkan tetapi kurang inisiatif. Opsi A, C, dan E masing-masing 1 poin karena menghindar, memaksa, atau menghindar."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam situasi di mana Anda harus mengambil risiko, bagaimana cara Anda mengevaluasi dan mengambil keputusan?",
                "opsi_a" => "Mengambil risiko tanpa pertimbangan",
                "opsi_b" => "Menganalisis risiko, mempertimbangkan manfaat, dan mengambil keputusan yang terukur",
                "opsi_c" => "Menghindari semua risiko",
                "opsi_d" => "Mendelegasikan pengambilan keputusan",
                "opsi_e" => "Mengikuti intuisi tanpa data",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan analisis yang matang, kehati-hatian, dan keberanian terukur. Opsi C mendapat 2 poin karena hati-hati tetapi kurang inisiatif. Opsi A, D, dan E masing-masing 1 poin karena ceroboh, menghindar, atau tidak rasional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda mengetahui bahwa ada pegawai yang melakukan kesalahan karena kurangnya pelatihan. Namun, instansi tidak memiliki anggaran pelatihan. Bagaimana tindakan Anda?",
                "opsi_a" => "Mengabaikan karena tidak ada anggaran",
                "opsi_b" => "Menjadi mentor sukarela, berbagi pengetahuan, dan mencari sumber belajar gratis",
                "opsi_c" => "Melaporkan pegawai tersebut ke atasan",
                "opsi_d" => "Menggunakan dana operasional untuk pelatihan",
                "opsi_e" => "Membiarkan pegawai tersebut terus melakukan kesalahan",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan inisiatif, orientasi pengembangan, dan kreativitas solusi. Opsi C mendapat 2 poin karena melaporkan tetapi kurang pendekatan edukatif. Opsi A, D, dan E masing-masing 1 poin karena tidak peduli, melanggar aturan, atau tidak bertanggung jawab."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam menghadapi klien yang marah karena pelayanan yang tidak memuaskan, bagaimana cara Anda menangani situasi ini?",
                "opsi_a" => "Membela diri dan menyalahkan klien",
                "opsi_b" => "Mendengarkan dengan empati, meminta maaf, dan mencari solusi",
                "opsi_c" => "Mengabaikan klien yang marah",
                "opsi_d" => "Melaporkan klien ke atasan",
                "opsi_e" => "Mengembalikan tanggung jawab kepada divisi lain",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan empati, orientasi pelayanan, dan kemampuan pemecahan masalah. Opsi D mendapat 2 poin karena melaporkan tetapi kurang inisiatif langsung. Opsi A, C, dan E masing-masing 1 poin karena defensif, tidak peduli, atau tidak bertanggung jawab."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda diminta untuk memimpin proyek dengan tim yang terdiri dari berbagai divisi dengan budaya kerja berbeda. Bagaimana cara Anda membangun kerjasama?",
                "opsi_a" => "Memaksakan budaya kerja satu divisi kepada semua",
                "opsi_b" => "Mengakui perbedaan, membangun visi bersama, dan mencari cara kerja yang inklusif",
                "opsi_c" => "Membagi tim berdasarkan divisi asal",
                "opsi_d" => "Menyerah karena perbedaan terlalu besar",
                "opsi_e" => "Mendelegasikan kepemimpinan kepada orang lain",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kepemimpinan inklusif, kemampuan manajemen keragaman, dan visi strategis. Opsi C mendapat 2 poin karena mengelola tetapi kurang integrasi. Opsi A, D, dan E masing-masing 1 poin karena otoriter, menyerah, atau menghindar."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam menghadapi kritik yang menyakitkan dari atasan, bagaimana cara Anda memproses dan merespons?",
                "opsi_a" => "Menyimpan dendam dan bersikap dingin",
                "opsi_b" => "Merefleksi kritik, mengambil pelajaran positif, dan memperbaiki diri",
                "opsi_c" => "Membela diri tanpa mendengarkan",
                "opsi_d" => "Mengeluh kepada rekan kerja",
                "opsi_e" => "Mengabaikan kritik sepenuhnya",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 1,
                "poin_e" => 2,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan maturity, sikap pembelajaran, dan orientasi perbaikan. Opsi E mendapat 2 poin karena mengabaikan tetapi tidak negatif. Opsi A, C, dan D masing-masing 1 poin karena dendam, defensif, atau tidak profesional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda mendapatkan kesempatan untuk mengambil kredit program pelatihan yang akan meningkatkan kompetensi Anda. Namun, program tersebut membutuhkan waktu di luar jam kerja. Bagaimana keputusan Anda?",
                "opsi_a" => "Menolak karena tidak mau lembur",
                "opsi_b" => "Menerima program sebagai investasi pengembangan diri dan mengatur waktu dengan baik",
                "opsi_c" => "Menerima tetapi tidak serius mengikuti",
                "opsi_d" => "Minta instansi membayar semua biaya",
                "opsi_e" => "Menggunakan jam kerja untuk mengikuti program",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan orientasi pembelajaran, inisiatif, dan manajemen waktu. Opsi D mendapat 2 poin karena realistis tetapi kurang komitmen pribadi. Opsi A, C, dan E masing-masing 1 poin karena tidak mau berkembang, tidak serius, atau tidak profesional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam situasi di mana Anda harus menyampaikan kabar buruk kepada tim, bagaimana cara Anda melakukannya?",
                "opsi_a" => "Menyampaikan dengan kasar dan langsung",
                "opsi_b" => "Menyampaikan dengan empati, transparansi, dan fokus pada solusi ke depan",
                "opsi_c" => "Mendelegasikan penyampaian kepada orang lain",
                "opsi_d" => "Menyembunyikan kabar buruk tersebut",
                "opsi_e" => "Menyampaikan sebagian informasi saja",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 1,
                "poin_e" => 2,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan empati, integritas, dan kepemimpinan yang konstruktif. Opsi E mendapat 2 poin karena transparansi sebagian tetapi kurang lengkap. Opsi A, C, dan D masing-masing 1 poin karena kasar, menghindar, atau tidak jujur."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda mengetahui bahwa ada pegawai yang melakukan bullying terhadap pegawai lain. Namun, pelaku adalah orang yang berpengaruh. Bagaimana tindakan Anda?",
                "opsi_a" => "Diam saja karena takut",
                "opsi_b" => "Melaporkan melalui kanal yang tepat dengan bukti dan melindungi korban",
                "opsi_c" => "Menghadapi pelaku langsung tanpa dukungan",
                "opsi_d" => "Mengabaikan karena itu konflik pribadi",
                "opsi_e" => "Bergabung dengan pelaku untuk menjaga posisi",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan integritas, keberanian, dan kepedulian. Opsi C mendapat 2 poin karena berani tetapi kurang strategis. Opsi A, D, dan E masing-masing 1 poin karena takut, tidak peduli, atau melanggar integritas."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam bekerja dengan klien yang sulit memenuhi deadline, bagaimana cara Anda menangani situasi ini?",
                "opsi_a" => "Memaksa klien dengan tekanan",
                "opsi_b" => "Mengkomunikasikan konsekuensi, mencari solusi bersama, dan membangun komitmen",
                "opsi_c" => "Mengabaikan deadline klien",
                "opsi_d" => "Melaporkan klien ke atasan",
                "opsi_e" => "Mengembalikan tanggung jawab kepada divisi lain",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kemampuan negosiasi, empati, dan orientasi solusi. Opsi D mendapat 2 poin karena melaporkan tetapi kurang inisiatif langsung. Opsi A, C, dan E masing-masing 1 poin karena memaksa, tidak profesional, atau tidak bertanggung jawab."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda diminta untuk menjadi mentor pegawai baru yang memiliki kemampuan di atas rata-rata tetapi sikapnya arogan. Bagaimana cara Anda membimbingnya?",
                "opsi_a" => "Mengabaikan pegawai baru tersebut",
                "opsi_b" => "Mendekati dengan humbleness, menghargai kemampuannya, dan membimbing sikapnya",
                "opsi_c" => "Menegur keras di depan umum",
                "opsi_d" => "Melaporkan sikap arogannya ke atasan",
                "opsi_e" => "Mendelegasikan mentoring kepada orang lain",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kepemimpinan yang matang, empati, dan kemampuan mengelola ego. Opsi D mendapat 2 poin karena melaporkan tetapi kurang pendekatan langsung. Opsi A, C, dan E masing-masing 1 poin karena tidak peduli, tidak profesional, atau menghindar."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam situasi di mana Anda harus memilih antara kejujuran dan menjaga hubungan dengan rekan kerja dekat, bagaimana keputusan Anda?",
                "opsi_a" => "Memilih menjaga hubungan dengan mengorbankan kejujuran",
                "opsi_b" => "Memilih kejujuran dan menjelaskan kepada rekan dengan cara yang membangun",
                "opsi_c" => "Menghindar dari situasi tersebut",
                "opsi_d" => "Memilih kejujuran tetapi dengan cara yang menyakiti",
                "opsi_e" => "Membocorkan informasi ke orang lain",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan integritas, kebijaksanaan, dan kemampuan komunikasi. Opsi D mendapat 2 poin karena jujur tetapi kurang empati. Opsi A, C, dan E masing-masing 1 poin karena melanggar integritas, menghindar, atau tidak profesional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda menemukan bahwa sistem pengarsipan instansi tidak efisien dan banyak waktu terbuang. Apa tindakan Anda yang paling tepat?",
                "opsi_a" => "Mengeluh tentang sistem yang tidak efisien",
                "opsi_b" => "Menganalisis kebutuhan, menyusun proposal perbaikan, dan menyampaikan kepada pihak berwenang",
                "opsi_c" => "Mengabaikan masalah dan mengikuti sistem yang ada",
                "opsi_d" => "Mengubah sistem sendiri tanpa persetujuan",
                "opsi_e" => "Mendelegasikan masalah kepada rekan kerja lain",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 1,
                "poin_e" => 2,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan inisiatif, analisis, dan pendekatan profesional. Opsi E mendapat 2 poin karena mencari bantuan tetapi kurang inisiatif. Opsi A, C, dan D masing-masing 1 poin karena negatif, pasif, atau tidak mengikuti prosedur."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Rekan kerja Anda selalu mengkritik ide Anda dalam setiap rapat, bahkan ketika ide tersebut bagus. Bagaimana cara Anda mengatasi situasi ini?",
                "opsi_a" => "Membalas kritik dengan kritik yang lebih keras",
                "opsi_b" => "Mendengarkan dengan terbuka, mencari kebenaran dalam kritik, dan berdiskusi konstruktif",
                "opsi_c" => "Berhenti mengajukan ide di rapat",
                "opsi_d" => "Mencela rekan tersebut di depan umum",
                "opsi_e" => "Melaporkan rekan tersebut ke atasan",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 1,
                "poin_e" => 2,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan sikap terbuka, profesionalisme, dan kemampuan berdiskusi. Opsi E mendapat 2 poin karena melaporkan tetapi kurang pendekatan langsung. Opsi A, C, dan D masing-masing 1 poin karena defensif, menyerah, atau tidak profesional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam menghadapi anggota tim yang tidak bertanggung jawab dan sering mengeluh, bagaimana cara Anda menangani situasi ini?",
                "opsi_a" => "Mengeluh juga tentang anggota tim tersebut",
                "opsi_b" => "Mengajak bicara dengan empati, memahami masalahnya, dan membantu mencari solusi",
                "opsi_c" => "Mengabaikan anggota tim tersebut",
                "opsi_d" => "Memecat anggota tim tersebut",
                "opsi_e" => "Melaporkan langsung ke atasan tanpa pendekatan",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 1,
                "poin_e" => 2,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kepemimpinan yang empatik, orientasi solusi, dan pendekatan edukatif. Opsi E mendapat 2 poin karena melaporkan tetapi kurang pendekatan langsung. Opsi A, C, dan D masing-masing 1 poin karena negatif, tidak peduli, atau terlalu keras."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda diminta untuk melakukan tugas yang membutuhkan keterampilan teknis yang Anda kuasai dengan baik, tetapi tidak dalam bidang yang Anda sukai. Bagaimana sikap Anda?",
                "opsi_a" => "Menolak karena tidak sesuai minat",
                "opsi_b" => "Menerima tugas dan mengeksekusi dengan profesionalisme tinggi",
                "opsi_c" => "Menerima tetapi mengerjakan dengan setengah hati",
                "opsi_d" => "Mendelegasikan kepada rekan lain",
                "opsi_e" => "Mengeluh tentang tugas tersebut",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan profesionalisme, tanggung jawab, dan orientasi hasil. Opsi D mendapat 2 poin karena mendelegasikan tetapi realistis. Opsi A, C, dan E masing-masing 1 poin karena tidak fleksibel, tidak profesional, atau negatif."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam situasi di mana Anda harus memilih antara loyalitas kepada instansi dan loyalitas kepada rekan kerja dekat yang melakukan kesalahan, bagaimana keputusan Anda?",
                "opsi_a" => "Memilih loyalitas kepada rekan kerja dan melindunginya",
                "opsi_b" => "Memilih loyalitas kepada instansi, tetapi tetap mendukung rekan untuk memperbaiki kesalahannya",
                "opsi_c" => "Menghindar dari membuat keputusan",
                "opsi_d" => "Memilih loyalitas kepada instansi dan membiarkan rekan menghadapi konsekuensi sendiri",
                "opsi_e" => "Membocorkan informasi kesalahan rekan ke publik",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan integritas, keseimbangan loyalitas, dan empati. Opsi D mendapat 2 poin karena benar tetapi kurang pendukungan. Opsi A, C, dan E masing-masing 1 poin karena melanggar integritas, menghindar, atau tidak profesional."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda mengetahui bahwa ada kebijakan baru yang akan menguntungkan instansi tetapi merugikan sebagian pegawai. Bagaimana cara Anda menyikapi kebijakan tersebut?",
                "opsi_a" => "Menentang kebijakan karena merugikan pegawai",
                "opsi_b" => "Mengimplementasikan kebijakan dengan adil, mencari kompensasi untuk pegawai yang terdampak",
                "opsi_c" => "Mengabaikan kebijakan tersebut",
                "opsi_d" => "Mengimplementasikan tanpa memperhatikan dampak",
                "opsi_e" => "Membocorkan kebijakan sebelum diumumkan",
                "jawaban_benar" => "B",
                "poin_a" => 2,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan keseimbangan, empati, dan kemampuan implementasi yang bijaksana. Opsi A mendapat 2 poin karena perduli tetapi kurang fleksibel. Opsi C, D, dan E masing-masing 1 poin karena menghindar, tidak peduli, atau melanggar prosedur."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam menghadapi perubahan teknologi yang cepat di tempat kerja, bagaimana sikap Anda untuk tetap relevan?",
                "opsi_a" => "Menolak belajar teknologi baru karena sudah nyaman dengan cara lama",
                "opsi_b" => "Aktif belajar teknologi baru, berbagi pengetahuan, dan membantu tim beradaptasi",
                "opsi_c" => "Mengikuti saja tanpa inisiatif",
                "opsi_d" => "Mengeluh tentang teknologi baru",
                "opsi_e" => "Mencari pekerjaan lain yang tidak butuh teknologi baru",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan adaptabilitas, inisiatif belajar, dan orientasi tim. Opsi C mendapat 2 poin karena mengikuti tetapi kurang proaktif. Opsi A, D, dan E masing-masing 1 poin karena resisten, negatif, atau menghindar."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda diminta untuk memimpin proyek dengan anggaran terbatas tetapi ekspektasi hasil tinggi. Bagaimana cara Anda mengelola proyek ini?",
                "opsi_a" => "Menolak proyek karena anggaran tidak cukup",
                "opsi_b" => "Mengoptimalkan sumber daya, memprioritaskan, dan mencari solusi kreatif dengan komunikasi transparan",
                "opsi_c" => "Mengerjakan proyek dengan kualitas rendah untuk menghemat anggaran",
                "opsi_d" => "Menggunakan dana lain tanpa izin",
                "opsi_e" => "Mengeluh tentang keterbatasan anggaran",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan manajemen sumber daya, kreativitas, dan komunikasi. Opsi A, C, D, dan E masing-masing 1 poin karena menolak, tidak profesional, melanggar aturan, atau negatif."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam situasi di mana Anda harus bekerja dengan atasan yang memiliki gaya kepemimpinan yang berbeda dari yang Anda sukai, bagaimana cara Anda beradaptasi?",
                "opsi_a" => "Menolak untuk beradaptasi dan tetap menggunakan cara sendiri",
                "opsi_b" => "Mempelajari gaya kepemimpinan atasan, mencari titik temu, dan mengkomunikasikan kebutuhan dengan sopan",
                "opsi_c" => "Mengikuti aturan atasan tanpa pemikiran",
                "opsi_d" => "Mengeluh kepada rekan kerja",
                "opsi_e" => "Mengabaikan instruksi atasan",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan adaptabilitas, kemampuan komunikasi, dan profesionalisme. Opsi C mendapat 2 poin karena taat tetapi kurang kritis. Opsi A, D, dan E masing-masing 1 poin karena tidak fleksibel, negatif, atau tidak patuh."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Anda menemukan bahwa ada informasi penting yang tertahan oleh divisi lain dan mempengaruhi kerja Anda. Bagaimana cara Anda menangani situasi ini?",
                "opsi_a" => "Mengambil informasi tanpa izin",
                "opsi_b" => "Mengkomunikasikan kebutuhan secara profesional, memahami kendala mereka, dan mencari solusi bersama",
                "opsi_c" => "Mengeluh tentang divisi lain",
                "opsi_d" => "Melaporkan divisi lain ke atasan tanpa pendekatan",
                "opsi_e" => "Menunggu informasi datang sendiri",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 1,
                "poin_d" => 2,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan kemampuan komunikasi, empati, dan orientasi kerjasama. Opsi D mendapat 2 poin karena melaporkan tetapi kurang pendekatan langsung. Opsi A, C, dan E masing-masing 1 poin karena melanggar aturan, negatif, atau pasif."
            ],
            [
                "kategori" => "TKP",
                "pertanyaan" => "Dalam menghadapi masa sulit di instansi, banyak pegawai mulai kehilangan semangat. Bagaimana cara Anda menjaga semangat dan memotivasi rekan kerja?",
                "opsi_a" => "Ikut kehilangan semangat dan mengeluh",
                "opsi_b" => "Menjadi teladan positif, berbagi perspektif optimis, dan mendukung rekan secara emosional",
                "opsi_c" => "Diam saja dan tidak peduli dengan rekan",
                "opsi_d" => "Menyerah dan mencari pekerjaan baru",
                "opsi_e" => "Mengeluh kepada rekan tentang keadaan instansi",
                "jawaban_benar" => "B",
                "poin_a" => 1,
                "poin_b" => 5,
                "poin_c" => 2,
                "poin_d" => 1,
                "poin_e" => 1,
                "pembahasan" => "Opsi B mendapat 5 poin karena menunjukkan sikap positif, kepemimpinan, dan empati. Opsi C mendapat 2 poin karena stabil tetapi kurang dukungan. Opsi A, D, dan E masing-masing 1 poin karena negatif, menyerah, atau merusak moral."
            ]
        ];

        foreach ($questions as $question) {
            Soal::create($question);
        }

        $this->command->info('70 TKP HOTS questions seeded successfully!');
    }
}
