<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Soal;

class TWKHOTSSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $questions = [
            [
                "kategori" => "TWK",
                "pertanyaan" => "Pancasila sebagai dasar negara Indonesia memiliki nilai filosofis yang mendalam. Sila ke-4 'Kemanusiaan yang adil dan beradab' memiliki makna fundamental dalam konteks hubungan antarmanusia. Manakah pernyataan yang paling tepat menggambarkan esensi sila ke-4 Pancasila?",
                "opsi_a" => "Menghargai martabat manusia tanpa membedakan suku, agama, ras, dan golongan",
                "opsi_b" => "Menjunjung tinggi nilai kemanusiaan dengan menjunjung tinggi harkat dan martabat manusia",
                "opsi_c" => "Mengakui persamaan derajat, hak, dan kewajiban antara sesama manusia",
                "opsi_d" => "Menempatkan kepentingan negara di atas kepentingan individu demi keutuhan bangsa",
                "opsi_e" => "Menghormati perbedaan pendapat dan keyakinan sebagai bagian dari kebebasan beragama",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena sila ke-4 Pancasila 'Kemanusiaan yang adil dan beradab' secara filosofis menekankan penghormatan terhadap martabat manusia (human dignity) sebagai nilai universal. Opsi A dan C juga berkaitan dengan kemanusiaan tetapi lebih spesifik pada aspek kesetaraan dan anti-diskriminasi. Opsi D lebih relevan dengan sila ke-3 (Persatuan Indonesia). Opsi E lebih relevan dengan sila ke-1 (Ketuhanan Yang Maha Esa) dan aspek kebebasan beragama."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah perjuangan bangsa Indonesia, Proklamasi Kemerdekaan 17 Agustus 1945 merupakan titik kulminasi dari perjuangan panjang bangsa. Peristiwa ini memiliki signifikansi historis yang mendalam. Manakah pernyataan yang paling tepat menggambarkan makna historis Proklamasi Kemerdekaan Indonesia?",
                "opsi_a" => "Merupakan pernyataan kemerdekaan yang disahkan oleh Jepang setelah kekalahan dalam Perang Dunia II",
                "opsi_b" => "Merupakan pernyataan kemerdekaan yang sah dan mengikat secara internasional sebagai negara berdaulat",
                "opsi_c" => "Merupakan pernyataan kemerdekaan yang dilakukan oleh Soekarno-Hatta atas nama bangsa Indonesia",
                "opsi_d" => "Merupakan pernyataan kemerdekaan yang menandai berakhirnya penjajahan Belanda di Indonesia",
                "opsi_e" => "Merupakan pernyataan kemerdekaan yang didasarkan pada kekosongan kekuasaan setelah menyerahnya Jepang",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Proklamasi Kemerdekaan 17 Agustus 1945 memiliki makna historis sebagai pernyataan kemerdekaan yang sah dan mengikat secara internasional, menjadikan Indonesia sebagai negara berdaulat yang diakui dunia. Opsi A salah karena Jepang tidak menyetujui proklamasi. Opsi C benar secara faktual tetapi kurang komprehensif. Opsi D tidak tepat karena penjajahan Belanda berakhir setelah perang kemerdekaan. Opsi E terlalu teknis dan tidak menangkap makna historis yang lebih dalam."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "UUD 1945 sebagai konstitusi negara Indonesia mengatur struktur ketatanegaraan dan hubungan antar lembaga negara. Pasal 1 ayat (1) UUD 1945 menyatakan bahwa 'Negara Indonesia ialah negara kesatuan yang berbentuk Republik'. Manakah implikasi paling tepat dari ketentuan tersebut?",
                "opsi_a" => "Indonesia tidak dapat membagi wilayahnya menjadi negara-negara bagian atau daerah otonom yang berdaulat",
                "opsi_b" => "Indonesia memiliki sistem pemerintahan republik dengan kepala negara dan kepala pemerintahan yang terpisah",
                "opsi_c" => "Indonesia memiliki kekuasaan yang terpusat di pemerintah pusat tanpa adanya otonomi daerah",
                "opsi_d" => "Indonesia mengakui keberadaan daerah istimewa dan daerah khusus dengan status yang berbeda",
                "opsi_e" => "Indonesia memiliki sistem multi-partai dengan demokrasi representatif",
                "jawaban_benar" => "A",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban A benar karena Pasal 1 ayat (1) UUD 1945 menegaskan Indonesia sebagai negara kesatuan (unitary state) yang berarti tidak dapat membagi wilayahnya menjadi negara-negara bagian. Opsi B salah karena itu bukan implikasi dari negara kesatuan. Opsi C salah karena Indonesia memiliki otonomi daerah. Opsi D benar secara faktual tetapi bukan implikasi langsung dari pasal tersebut. Opsi E tidak relevan dengan ketentuan negara kesatuan."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Bhinneka Tunggal Ika sebagai semboyan negara Indonesia memiliki makna filosofis yang mendalam dalam konteks keberagaman bangsa. Semboyan ini diambil dari kitab Sutasoma karya Mpu Tantular. Manakah pernyataan yang paling tepat menggambarkan esensi Bhinneka Tunggal Ika?",
                "opsi_a" => "Mengakui dan menghargai perbedaan suku, agama, ras, dan golongan sebagai kekayaan bangsa",
                "opsi_b" => "Menyatukan perbedaan dalam satu kesatuan yang utuh meskipun beragam",
                "opsi_c" => "Mengutamakan persatuan dan kesatuan di atas perbedaan yang ada",
                "opsi_d" => "Menghapus perbedaan untuk mencapai kesatuan yang mutlak",
                "opsi_e" => "Mengakui bahwa perbedaan adalah hal yang wajar dalam masyarakat majemuk",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Bhinneka Tunggal Ika secara filosofis berarti 'berbeda-beda tetapi tetap satu juga' - menekankan persatuan dalam keberagaman. Opsi A dan C juga berkaitan tetapi kurang menangkap esensi filosofis. Opsi D salah karena semboyan ini tidak menghapus perbedaan. Opsi E terlalu umum dan tidak menangkap makna persatuan."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Sistem pemerintahan Indonesia berdasarkan UUD 1945 menganut sistem presidensial. Dalam sistem ini, Presiden memiliki kedudukan sebagai kepala negara sekaligus kepala pemerintahan. Manakah pernyataan yang paling tepat menggambarkan karakteristik sistem presidensial Indonesia?",
                "opsi_a" => "Presiden bertanggung jawab kepada DPR dan dapat diberhentikan melalui mosi tidak percaya",
                "opsi_b" => "Presiden memiliki kekuasaan eksekutif yang kuat dan tidak dapat diintervensi oleh lembaga legislatif",
                "opsi_c" => "Presiden dipilih langsung oleh rakyat dan memiliki masa jabatan tertentu",
                "opsi_d" => "Presiden membentuk kabinet dengan menteri yang bertanggung jawab kepada Presiden",
                "opsi_e" => "Presiden memiliki hak veto terhadap produk legislasi dari DPR",
                "jawaban_benar" => "D",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban D benar karena dalam sistem presidensial, menteri bertanggung jawab kepada Presiden, bukan kepada DPR. Opsi A salah karena itu ciri sistem parlementer. Opsi B salah karena Presiden tetap dapat diintervensi melalui mekanisme checks and balances. Opsi C benar secara faktual tetapi bukan karakteristik utama sistem presidensial. Opsi E salah karena Presiden tidak memiliki hak veto mutlak."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks hubungan internasional, Indonesia menerapkan politik luar negeri yang bebas aktif. Politik ini pertama kali diumumkan oleh Mohammad Hatta pada tahun 1948. Manakah pernyataan yang paling tepat menggambarkan esensi politik luar negeri bebas aktif Indonesia?",
                "opsi_a" => "Indonesia tidak berpihak pada blok manapun dalam Perang Dingin dan berusaha netral",
                "opsi_b" => "Indonesia bebas menentukan sikap dalam hubungan internasional berdasarkan kepentingan nasional",
                "opsi_c" => "Indonesia aktif berpartisipasi dalam organisasi internasional untuk memperjuangkan kepentingan bangsa",
                "opsi_d" => "Indonesia mengutamakan kerjasama regional dengan negara-negara Asia Tenggara",
                "opsi_e" => "Indonesia menolak intervensi asing dalam urusan internal negara",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena politik luar negeri bebas aktif berarti Indonesia bebas menentukan sikap berdasarkan kepentingan nasional, bukan tekanan blok manapun. Opsi A terlalu sempit karena 'bebas' bukan berarti netral pasif. Opsi C menekankan aspek 'aktif' tetapi kurang menangkap aspek 'bebas'. Opsi D terlalu spesifik pada ASEAN. Opsi E bukan esensi politik luar negeri bebas aktif."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Hamka adalah salah satu ulama dan sastrawan besar Indonesia yang memiliki kontribusi signifikan dalam perkembangan pemikiran Islam dan sastra Indonesia. Karya-karyanya mencerminkan pemikiran yang mendalam tentang Islam dan kebangsaan. Manakah pernyataan yang paling tepat menggambarkan kontribusi Hamka?",
                "opsi_a" => "Menulis novel 'Tenggelamnya Kapal Van Der Wijck' yang menggambarkan kehidupan masyarakat Minangkabau",
                "opsi_b" => "Menulis tafsir Al-Quran 'Tafsir Al-Azhar' yang menghubungkan Islam dengan konteks Indonesia",
                "opsi_c" => "Menjadi pemimpin Muhammadiyah dan memperjuangkan pendidikan Islam modern",
                "opsi_d" => "Menulis esai-esai tentang pemikiran Islam dan kebangsaan di majalah Panji Masyarakat",
                "opsi_e" => "Menjadi tokoh reformasi Islam yang mengkritik praktik-praktik tradisional",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Tafsir Al-Azhar adalah karya monumental Hamka yang menghubungkan pemikiran Islam dengan konteks Indonesia, menunjukkan kemampuan ijtihad dan pemikiran yang orisinal. Opsi A benar secara faktual tetapi itu karya sastra, bukan kontribusi pemikiran Islam. Opsi C benar tetapi lebih fokus pada organisasi. Opsi D dan E kurang komprehensif dibandingkan Tafsir Al-Azhar."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah pergerakan nasional Indonesia, Sumpah Pemuda 1928 merupakan peristiwa penting yang mempercepat proses persatuan bangsa. Sumpah Pemuda terdiri dari tiga butir yang menegaskan kesatuan bangsa. Manakah pernyataan yang paling tepat menggambarkan makna Sumpah Pemuda?",
                "opsi_a" => "Menyatukan berbagai organisasi pemuda di bawah satu wadah pergerakan nasional",
                "opsi_b" => "Menegaskan kesatuan bangsa, tanah air, dan bahasa sebagai satu kesatuan Indonesia",
                "opsi_c" => "Menghapus perbedaan suku, agama, ras, dan golongan dalam pergerakan nasional",
                "opsi_d" => "Menyatakan kemerdekaan Indonesia dari penjajahan Belanda",
                "opsi_e" => "Membentuk negara Indonesia yang berdaulat dan merdeka",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Sumpah Pemuda menegaskan tiga butir: satu tanah air, satu bangsa, dan satu bahasa - Indonesia. Opsi A salah karena Sumpah Pemuda tidak menyatukan organisasi. Opsi C salah karena Sumpah Pemuda tidak menghapus perbedaan. Opsi D dan E salah karena Sumpah Pemuda bukan pernyataan kemerdekaan."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sistem ketatanegaraan Indonesia, MPR (Majelis Permusyawaratan Rakyat) memiliki kedudukan sebagai lembaga tertinggi negara. Namun, setelah amandemen UUD 1945, kedudukan MPR mengalami perubahan. Manakah pernyataan yang paling tepat menggambarkan kedudukan MPR setelah amandemen?",
                "opsi_a" => "MPR tetap sebagai lembaga tertinggi negara dengan kekuasaan mutlak",
                "opsi_b" => "MPR menjadi lembaga negara yang setara dengan lembaga negara lain",
                "opsi_c" => "MPR hanya berfungsi sebagai lembaga pemilihan Presiden dan Wakil Presiden",
                "opsi_d" => "MPR memiliki kekuasaan untuk mengubah UUD 1945 tanpa batasan",
                "opsi_e" => "MPR dapat memberhentikan Presiden kapan saja tanpa alasan yang jelas",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena setelah amandemen, MPR tidak lagi sebagai lembaga tertinggi negara tetapi setara dengan lembaga negara lain dalam sistem checks and balances. Opsi A salah karena MPR tidak lagi lembaga tertinggi. Opsi C salah karena MPR masih memiliki fungsi lain. Opsi D salah karena perubahan UUD dibatasi. Opsi E salah karena mekanisme pemberhentian Presiden diatur ketat."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dewan Pertimbangan Agung (DPA) adalah lembaga negara yang diatur dalam UUD 1945. DPA memiliki fungsi memberikan nasihat dan pertimbangan kepada Presiden. Manakah pernyataan yang paling tepat menggambarkan karakteristik DPA?",
                "opsi_a" => "DPA adalah lembaga legislatif yang membentuk undang-undang bersama Presiden",
                "opsi_b" => "DPA adalah lembaga yudikatif yang memutuskan sengketa hukum",
                "opsi_c" => "DPA adalah lembaga yang memberikan nasihat dan pertimbangan kepada Presiden sesuai permintaan",
                "opsi_d" => "DPA adalah lembaga eksekutif yang menjalankan kekuasaan pemerintahan",
                "opsi_e" => "DPA adalah lembaga pengawas yang mengawasi kinerja pemerintah",
                "jawaban_benar" => "C",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban C benar karena DPA adalah lembaga negara yang memberikan nasihat dan pertimbangan kepada Presiden sesuai permintaan. Opsi A salah karena itu fungsi DPR. Opsi B salah karena itu fungsi Mahkamah Agung. Opsi D salah karena itu fungsi Presiden dan kabinet. Opsi E salah karena itu fungsi DPR dan BPK."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah perjuangan Indonesia, Perang Diponegoro (1825-1830) merupakan perlawanan bersenjata terbesar melawan kolonial Belanda. Perang ini dipicu oleh berbagai faktor. Manakah faktor yang paling utama menjadi pemicu Perang Diponegoro?",
                "opsi_a" => "Penyebaran agama Islam yang dihalangi oleh Belanda",
                "opsi_b" => "Kebijakan Belanda yang merugikan rakyat dan kerajaan",
                "opsi_c" => "Perebutan kekuasaan antara kerajaan-kerajaan Jawa",
                "opsi_d" => "Intervensi Inggris dalam urusan internal kerajaan",
                "opsi_e" => "Kebijakan tanam paksa yang merugikan petani",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Perang Diponegoro dipicu oleh kebijakan Belanda yang merugikan rakyat dan kerajaan, terutama masalah jalan, pajak, dan monopoli. Opsi A salah karena bukan faktor utama. Opsi C salah karena perang bukan perebutan kekuasaan antar kerajaan. Opsi D salah karena Inggris bukan faktor utama. Opsi E salah karena tanam paksa belum diterapkan saat itu."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks HAM (Hak Asasi Manusia), Indonesia telah meratifikasi berbagai instrumen internasional HAM. UUD 1945 juga mengatur tentang HAM dalam Pasal 28A sampai 28J. Manakah pernyataan yang paling tepat menggambarkan karakteristik pengaturan HAM dalam UUD 1945?",
                "opsi_a" => "HAM dapat dibatasi demi kepentingan keamanan dan ketertiban umum",
                "opsi_b" => "HAM adalah hak yang melekat pada manusia dan tidak dapat diabaikan",
                "opsi_c" => "HAM hanya berlaku untuk warga negara Indonesia",
                "opsi_d" => "HAM dapat dicabut oleh negara dalam keadaan darurat",
                "opsi_e" => "HAM bersifat absolut dan tidak dapat dibatasi dalam kondisi apapun",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Pasal 28A UUD 1945 menyatakan HAM adalah hak yang melekat pada manusia dan tidak dapat diabaikan. Opsi A salah karena pembatasan HAM diatur ketat. Opsi C salah karena HAM berlaku universal. Opsi D salah karena HAM tidak dapat dicabut. Opsi E salah karena HAM dapat dibatasi dalam kondisi tertentu."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sistem ekonomi Indonesia, UUD 1945 Pasal 33 mengatur tentang perekonomian nasional. Pasal ini menegaskan prinsip ekonomi yang berbeda dengan sistem kapitalis atau sosialis. Manakah pernyataan yang paling tepat menggambarkan esensi Pasal 33 UUD 1945?",
                "opsi_a" => "Perekonomian disusun sebagai usaha bersama berdasarkan asas kekeluargaan",
                "opsi_b" => "Cabang-cabang produksi penting dikuasai negara dan dimanfaatkan untuk sebesar-besar kemakmuran rakyat",
                "opsi_c" => "Bumi, air, dan kekayaan alam dikuasai negara dan dimanfaatkan untuk sebesar-besar kemakmuran rakyat",
                "opsi_d" => "Perekonomian nasional berlandaskan demokrasi ekonomi dengan persaingan yang sehat",
                "opsi_e" => "Negara memiliki peran penting dalam mengatur dan mengendalikan perekonomian",
                "jawaban_benar" => "A",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban A benar karena Pasal 33 ayat (1) UUD 1945 menegaskan perekonomian disusun sebagai usaha bersama berdasarkan asas kekeluargaan - esensi ekonomi Indonesia. Opsi B dan C benar secara faktual tetapi itu detail dari Pasal 33. Opsi D dan E tidak secara langsung menyebut esensi Pasal 33."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah pergerakan nasional, Budi Utomo adalah organisasi pergerakan nasional pertama yang didirikan pada tahun 1908. Organisasi ini memiliki peran penting dalam membangkitkan kesadaran nasional. Manakah pernyataan yang paling tepat menggambarkan karakteristik Budi Utomo?",
                "opsi_a" => "Organisasi politik yang memperjuangkan kemerdekaan Indonesia",
                "opsi_b" => "Organisasi sosial pendidikan yang memajukan pendidikan dan kebudayaan Jawa",
                "opsi_c" => "Organisasi keagamaan yang menyebarkan Islam di Indonesia",
                "opsi_d" => "Organisasi pemuda yang memperjuangkan persatuan bangsa",
                "opsi_e" => "Organisasi buruh yang memperjuangkan hak-hak pekerja",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Budi Utomo adalah organisasi sosial pendidikan yang berfokus pada memajukan pendidikan dan kebudayaan Jawa, bukan organisasi politik. Opsi A salah karena Budi Utomo bukan organisasi politik. Opsi C salah karena bukan organisasi keagamaan. Opsi D salah karena itu Sumpah Pemuda. Opsi E salah karena itu organisasi buruh."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sistem ketatanegaraan Indonesia, Komisi Yudisial adalah lembaga negara yang dibentuk setelah amandemen UUD 1945. Komisi Yudisial memiliki fungsi mengawasi perilaku hakim. Manakah pernyataan yang paling tepat menggambarkan karakteristik Komisi Yudisial?",
                "opsi_a" => "Komisi Yudisial memiliki kekuasaan untuk memutuskan sengketa hukum",
                "opsi_b" => "Komisi Yudisial memiliki kekuasaan untuk memberhentikan hakim tanpa proses hukum",
                "opsi_c" => "Komisi Yudisial memiliki fungsi mengusulkan pengangkatan dan pemberhentian hakim",
                "opsi_d" => "Komisi Yudisial memiliki kekuasaan untuk mengubah undang-undang",
                "opsi_e" => "Komisi Yudisial memiliki fungsi mengawasi kinerja pemerintah",
                "jawaban_benar" => "C",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban C benar karena Komisi Yudisial memiliki fungsi mengusulkan pengangkatan dan pemberhentian hakim kepada DPR dan Presiden. Opsi A salah karena itu fungsi Mahkamah Agung. Opsi B salah karena pemberhentian harus melalui proses hukum. Opsi D salah karena itu fungsi DPR. Opsi E salah karena itu fungsi DPR dan BPK."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah perjuangan Indonesia, Perang Aceh (1873-1904) merupakan perlawanan sengit melawan kolonial Belanda. Perang ini dipimpin oleh ulama-ulama Aceh yang memperjuangkan agama dan tanah air. Manakah faktor yang paling utama menjadi pemicu Perang Aceh?",
                "opsi_a" => "Perebutan kekuasaan antara ulama dan sultan",
                "opsi_b" => "Kebijakan Belanda yang mengancam kedaulatan dan agama Islam",
                "opsi_c" => "Intervensi Inggris dalam urusan internal Aceh",
                "opsi_d" => "Konflik antara Aceh dan kerajaan tetangga",
                "opsi_e" => "Kebijakan tanam paksa yang merugikan petani",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Perang Aceh dipicu oleh kebijakan Belanda yang mengancam kedaulatan Aceh dan agama Islam, terutama perjanjian yang merugikan. Opsi A salah karena bukan faktor utama. Opsi C salah karena Inggris bukan faktor utama. Opsi D salah karena bukan konflik antar kerajaan. Opsi E salah karena tanam paksa belum diterapkan."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks pertahanan negara, Indonesia memiliki konsep Pertahanan Semesta yang diatur dalam UUD 1945. Konsep ini menekankan partisipasi seluruh rakyat dalam pertahanan negara. Manakah pernyataan yang paling tepat menggambarkan esensi Pertahanan Semesta?",
                "opsi_a" => "Pertahanan negara hanya dilakukan oleh TNI dan POLRI",
                "opsi_b" => "Pertahanan negara dilakukan oleh seluruh rakyat dengan TNI sebagai komponen utama",
                "opsi_c" => "Pertahanan negara dilakukan secara profesional oleh militer",
                "opsi_d" => "Pertahanan negara hanya dilakukan dalam keadaan perang",
                "opsi_e" => "Pertahanan negara dilakukan dengan bantuan negara asing",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Pertahanan Semesta menekankan partisipasi seluruh rakyat dengan TNI sebagai komponen utama, bukan hanya militer. Opsi A salah karena bukan hanya TNI dan POLRI. Opsi C salah karena bukan hanya profesional militer. Opsi D salah karena pertahanan dilakukan setiap saat. Opsi E salah karena pertahanan mandiri."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah pergerakan nasional, Sarekat Islam adalah organisasi pergerakan nasional terbesar sebelum kemerdekaan. Organisasi ini memiliki peran penting dalam membangkitkan kesadaran nasional dan ekonomi. Manakah pernyataan yang paling tepat menggambarkan karakteristik Sarekat Islam?",
                "opsi_a" => "Organisasi politik yang memperjuangkan kemerdekaan Indonesia",
                "opsi_b" => "Organisasi ekonomi yang memperjuangkan kesejahteraan pedagang pribumi",
                "opsi_c" => "Organisasi keagamaan yang menyebarkan Islam di Indonesia",
                "opsi_d" => "Organisasi pemuda yang memperjuangkan persatuan bangsa",
                "opsi_e" => "Organisasi buruh yang memperjuangkan hak-hak pekerja",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Sarekat Islam awalnya adalah organisasi ekonomi yang memperjuangkan kesejahteraan pedagang pribumi dari persaingan pedagang Tionghoa dan Belanda. Opsi A salah karena awalnya bukan organisasi politik. Opsi C salah karena bukan hanya organisasi keagamaan. Opsi D salah karena itu Sumpah Pemuda. Opsi E salah karena itu organisasi buruh."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sistem ketatanegaraan Indonesia, Mahkamah Konstitusi adalah lembaga negara yang dibentuk setelah amandemen UUD 1945. Mahkamah Konstitusi memiliki fungsi menguji undang-undang terhadap UUD 1945. Manakah pernyataan yang paling tepat menggambarkan karakteristik Mahkamah Konstitusi?",
                "opsi_a" => "Mahkamah Konstitusi memiliki kekuasaan untuk memutuskan sengketa hukum biasa",
                "opsi_b" => "Mahkamah Konstitusi memiliki kekuasaan untuk mengubah UUD 1945",
                "opsi_c" => "Mahkamah Konstitusi memiliki fungsi menguji undang-undang terhadap UUD 1945",
                "opsi_d" => "Mahkamah Konstitusi memiliki kekuasaan untuk membentuk undang-undang",
                "opsi_e" => "Mahkamah Konstitusi memiliki fungsi mengawasi kinerja pemerintah",
                "jawaban_benar" => "C",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban C benar karena Mahkamah Konstitusi memiliki fungsi judicial review - menguji undang-undang terhadap UUD 1945. Opsi A salah karena itu fungsi Mahkamah Agung. Opsi B salah karena itu fungsi MPR. Opsi D salah karena itu fungsi DPR. Opsi E salah karena itu fungsi DPR dan BPK."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah perjuangan Indonesia, Perang Jawa (1825-1830) atau Perang Diponegoro memiliki dampak signifikan terhadap kebijakan kolonial Belanda. Manakah dampak yang paling utama dari Perang Diponegoro?",
                "opsi_a" => "Belanda mengakhiri sistem tanam paksa di Jawa",
                "opsi_b" => "Belanda mengubah kebijakan kolonial menjadi lebih lunak",
                "opsi_c" => "Belanda memperketat kontrol dan memperluas kekuasaan di Jawa",
                "opsi_d" => "Belanda menarik pasukan dari Jawa",
                "opsi_e" => "Belanda memberikan otonomi kepada kerajaan Jawa",
                "jawaban_benar" => "C",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban C benar karena setelah Perang Diponegoro, Belanda memperketat kontrol dan memperluas kekuasaan di Jawa dengan sistem Cultuurstelsel (Tanam Paksa). Opsi A salah karena tanam paksa justru diterapkan setelah perang. Opsi B salah karena kebijakan menjadi lebih keras. Opsi D salah karena Belanda menambah pasukan. Opsi E salah karena otonomi dikurangi."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks reformasi 1998, salah satu perubahan fundamental yang terjadi adalah terkait kekuasaan legislatif. Perubahan apa yang paling signifikan dalam struktur kekuasaan negara setelah reformasi?",
                "opsi_a" => "Penghapusan kekuasaan MPR untuk memilih Presiden",
                "opsi_b" => "Penghapusan kekuasaan DPR untuk mengawasi pemerintah",
                "opsi_c" => "Perubahan sistem pemilihan Presiden dari oleh MPR menjadi langsung oleh rakyat",
                "opsi_d" => "Penghapusan fungsi pembentukan undang-undang oleh DPR",
                "opsi_e" => "Pemindahan kekuasaan eksekutif dari Presiden ke DPR",
                "jawaban_benar" => "C",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban C benar karena amandemen UUD 1945 mengubah sistem pemilihan Presiden dari oleh MPR menjadi pemilihan langsung oleh rakyat (Pemilu Presiden). Opsi A salah karena MPR masih memiliki fungsi pelantikan. Opsi B dan D salah karena DPR tetap memiliki fungsi pengawasan dan legislasi. Opsi E salah karena kekuasaan eksekutif tetap di Presiden."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Konsep negara kesatuan dalam sistem ketatanegaraan Indonesia memiliki karakteristik khusus dibandingkan dengan negara federal. Manakah yang paling tepat menggambarkan ciri negara kesatuan Indonesia?",
                "opsi_a" => "Daerah memiliki kekuasaan untuk memisahkan diri dari negara pusat",
                "opsi_b" => "Daerah memiliki kedaulatan yang sama dengan pusat dalam hubungan luar negeri",
                "opsi_c" => "Pemerintah daerah diberikan otonomi luas namun tetap dalam satu kesatuan negara",
                "opsi_d" => "Pemerintah pusat tidak memiliki kewenangan dalam urusan daerah",
                "opsi_e" => "Setiap daerah memiliki konstitusi sendiri yang berbeda dari pusat",
                "jawaban_benar" => "C",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban C benar karena Indonesia adalah negara kesatuan dengan sistem desentralisasi - daerah memiliki otonomi namun tetap dalam satu kesatuan. Opsi A, B, D, dan E adalah ciri negara federal, bukan negara kesatuan."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah Indonesia modern, peristiwa G30S 1965 memiliki dampak signifikan terhadap arah politik negara. Manakah dampak paling fundamental dari peristiwa tersebut?",
                "opsi_a" => "Penguatan ideologi komunis di Indonesia",
                "opsi_b" => "Pergeseran politik luar negeri Indonesia ke Barat dan pembubaran PKI",
                "opsi_c" => "Pemisahan Timor Timur dari Indonesia",
                "opsi_d" => "Jatuhnya Orde Baru dan munculnya Orde Reformasi",
                "opsi_e" => "Pengakuan kedaulatan Indonesia oleh Belanda",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena setelah G30S, Indonesia mengubah orientasi politiknya, memusuhi komunis, dan bergabung dengan blok Barat. PKI dibubarkan dan anggotanya dianiaya. Opsi A salah karena komunis diberantas. Opsi C terjadi 1975. Opsi D terjadi 1998. Opsi E terjadi 1949."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Konstitusi RIS (Republik Indonesia Serikat) yang berlaku 1949-1950 mencerminkan struktur politik Indonesia pada masa tertentu. Manakah karakteristik paling menonjol dari konstitusi ini?",
                "opsi_a" => "Indonesia sebagai negara kesatuan dengan sistem presidensial",
                "opsi_b" => "Indonesia sebagai negara federal dengan berbagai negara bagian",
                "opsi_c" => "Indonesia sebagai negara kerajaan dengan sistem monarki",
                "opsi_d" => "Indonesia sebagai negara komunis dengan sistem partai tunggal",
                "opsi_e" => "Indonesia sebagai negara koloni dengan pemerintahan Belanda",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena RIS adalah struktur federal dengan negara-negara bagian seperti Republik Indonesia, negara-negara di Sumatera, dan daerah-daerah istimewa. Opsi A salah karena itu UUD 1945. Opsi C, D, dan E tidak sesuai sejarah."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam perspektif geopolitik, letak geografis Indonesia memiliki signifikansi strategis. Manakah faktor paling penting yang menjadikan Indonesia penting dalam politik internasional?",
                "opsi_a" => "Indonesia terletak di kutub selatan dengan sumber daya es yang melimpah",
                "opsi_b" => "Indonesia terletak di persimpangan jalur perdagangan internasional dan memiliki sumber daya alam strategis",
                "opsi_c" => "Indonesia terletak di benua Eropa dengan industri maju",
                "opsi_d" => "Indonesia terletak di gurun dengan cadangan minyak terbesar",
                "opsi_e" => "Indonesia terletak di pegunungan Himalaya dengan ketinggian ekstrem",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Indonesia terletak di jalur vital Selat Malaka dan memiliki sumber daya alam strategis (minyak, gas, timah, nikel). Opsi A, C, D, dan E salah secara geografis."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah pergerakan nasional, peran pergerakan perempuan memiliki kontribusi signifikan. Organisasi perempuan mana yang pertama kali menuntut hak politik bagi perempuan Indonesia?",
                "opsi_a" => "Dharma Wanita",
                "opsi_b" => "Gerwani",
                "opsi_c" => "Pergerakan Perempuan Indonesia",
                "opsi_d" => "Aisyiyah",
                "opsi_e" => "Kowani",
                "jawaban_benar" => "C",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban C benar karena Pergerakan Perempuan Indonesia (1928) yang dipelopori oleh Maria Ulfah Santoso menuntut hak politik perempuan. Opsi A adalah organisasi istri pejabat. Opsi B adalah organisasi wanita komunis. Opsi D adalah organisasi Muhammadiyah. Opsi E adalah kongres wanita."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks sejarah Indonesia, Konferensi Asia-Afrika 1955 di Bandung memiliki makna historis penting. Manakah kontribusi paling signifikan dari konferensi ini bagi Indonesia?",
                "opsi_a" => "Pengakuan kedaulatan Indonesia oleh Belanda",
                "opsi_b" => "Pembentukan blok militer bersama negara-negara Asia-Afrika",
                "opsi_c" => "Mengukuhkan Indonesia sebagai pemimpin negara-negara berkembang dan inisiasi Gerakan Non-Blok",
                "opsi_d" => "Penandatanganan perjanjian perdagangan bebas dengan Eropa",
                "opsi_e" => "Pembagian wilayah kekuasaan antara Indonesia dan Belanda",
                "jawaban_benar" => "C",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban C benar karena Konferensi Asia-Afrika melahirkan Dasasila Bandung dan menjadi cikal bakal Gerakan Non-Blok. Indonesia dipandang sebagai pemimpin negara berkembang. Opsi A terjadi 1949. Opsi B, D, dan E bukan hasil konferensi."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Sistem pemerintahan Indonesia menganut sistem presidensial namun dengan ciri khas tertentu. Manakah ciri khas paling menonjol dari sistem presidensial Indonesia dibandingkan dengan sistem presidensial Amerika Serikat?",
                "opsi_a" => "Presiden Indonesia dipilih oleh parlemen, bukan oleh rakyat langsung",
                "opsi_b" => "Presiden Indonesia memiliki kekuasaan lebih terbatas dari Presiden Amerika",
                "opsi_c" => "Presiden Indonesia merupakan kepala negara sekaligus kepala pemerintahan seperti di Amerika",
                "opsi_d" => "Presiden Indonesia dipilih langsung oleh rakyat tetapi memiliki kekuasaan yang terbatas oleh parlemen",
                "opsi_e" => "Presiden Indonesia dipilih oleh parlemen dan tidak memiliki kekuasaan eksekutif",
                "jawaban_benar" => "D",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban D benar karena setelah amandemen UUD 1945, Presiden dipilih langsung rakyat (sejak 2004). Namun kekuasannya tetap terbatas oleh sistem checks and balances dengan DPR. Opsi A salah karena sekarang pemilihan langsung. Opsi B salah karena Indonesia presidensial murni. Opsi C benar untuk Amerika juga. Opsi E salah karena Presiden memiliki kekuasaan eksekutif."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks sejarah, kebijakan Etis yang diusulkan oleh Queen Wilhelmina tahun 1901 memiliki dampak signifikan. Manakah dampak paling langsung dari kebijakan ini bagi Indonesia?",
                "opsi_a" => "Penghapusan pajak dan pembebasan tenaga kerja paksa",
                "opsi_b" => "Pengembangan pendidikan, kesehatan, dan transmigrasi untuk kepentingan Belanda",
                "opsi_c" => "Pengakuan kemerdekaan Indonesia oleh Belanda",
                "opsi_d" => "Penghapusan monopoli perdagangan Belanda di Indonesia",
                "opsi_e" => "Pemindahan ibu kota Hindia Belanda ke Indonesia",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Kebijakan Etis terdiri dari tiga program: Education (pendidikan), Emigration (transmigrasi), dan Irrigation (irigasi). Semuanya untuk kepentingan Belanda jangka panjang. Opsi A, C, D, dan E tidak terjadi atau bukan hasil kebijakan etis."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sistem ketatanegaraan, Undang-Undang Dasar 1945 memiliki kedudukan sebagai hukum tertinggi. Manakah implikasi dari kedudukan UUD 1945 sebagai hukum dasar negara?",
                "opsi_a" => "UUD 1945 hanya berlaku untuk warga negara Indonesia saja",
                "opsi_b" => "Semua peraturan perundang-undangan harus bersumber dan tidak boleh bertentangan dengan UUD 1945",
                "opsi_c" => "UUD 1945 dapat diubah oleh Peraturan Pemerintah",
                "opsi_d" => "UUD 1945 hanya berlaku di wilayah Jawa dan Madura",
                "opsi_e" => "UUD 1945 tidak mengikat aparatur negara",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena UUD 1945 adalah hukum tertinggi (supreme law) sehingga semua peraturan harus sesuai dan tidak boleh bertentangan (Pasal 7A UUD 1945, asas hierarchie van regelementen). Opsi A salah karena berlaku umum. Opsi C salah karena hanya bisa diubah oleh MPR. Opsi D dan E salah secara konstitusional."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah pergerakan nasional, peristiwa Peristiwa Rengasdengklok 1945 memiliki makna penting. Apa tujuan utama dari peristiwa ini?",
                "opsi_a" => "Memaksa Sukarno-Hatta untuk segera memproklamasikan kemerdekaan Indonesia",
                "opsi_b" => "Menggulingkan pemerintahan Sukarno-Hatta",
                "opsi_c" => "Membentuk organisasi pemuda nasional",
                "opsi_d" => "Melakukan perundingan dengan Belanda",
                "opsi_e" => "Mendirikan partai politik baru",
                "jawaban_benar" => "A",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban A benar karena para pemuda membawa Sukarno-Hatta ke Rengasdengklok untuk memaksa mereka segera memproklamasikan kemerdekaan sebelum Sekutu datang. Opsi B salah karena tujuannya bukan menggulingkan. Opsi C, D, dan E tidak sesuai konteks."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks sejarah, peristiwa Konferensi Meja Bundar 1949 memiliki dampak signifikan. Manakah hasil paling penting dari konferensi ini?",
                "opsi_a" => "Pengakuan kedaulatan Indonesia oleh Belanda dengan pembentukan RIS",
                "opsi_b" => "Pengakuan kemerdekaan Indonesia oleh Jepang",
                "opsi_c" => "Pembentukan Republik Indonesia Serikat sebagai negara federal permanen",
                "opsi_d" => "Pembagian wilayah Indonesia menjadi dua negara",
                "opsi_e" => "Pengakuan Indonesia sebagai anggota PBB",
                "jawaban_benar" => "A",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban A benar karena KMB 1949 menghasilkan pengakuan kedaulatan Indonesia oleh Belanda dengan pembentukan RIS sebagai negara federal. Opsi B salah karena Jepang sudah kalah perang. Opsi C salah karena RIS tidak permanen. Opsi D salah karena Indonesia tetap utuh. Opsi E terjadi 1950."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sistem ketatanegaraan Indonesia, MPR memiliki fungsi penting yang berbeda dengan DPR. Manakah perbedaan paling fundamental antara MPR dan DPR?",
                "opsi_a" => "MPR memiliki kekuasaan untuk membentuk undang-undang sehari-hari",
                "opsi_b" => "MPR memiliki kekuasaan untuk mengubah dan menetapkan UUD serta melantik Presiden",
                "opsi_c" => "MPR memiliki kekuasaan untuk mengawasi pemerintah sehari-hari",
                "opsi_d" => "MPR tidak memiliki kewenangan dalam sistem ketatanegaraan",
                "opsi_e" => "MPR hanya berfungsi sebagai lembaga penasihat",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena MPR adalah lembaga tertinggi negara yang berwenang mengubah dan menetapkan UUD, melantik dan memberhentikan Presiden. Opsi A dan C adalah fungsi DPR. Opsi D dan E salah konstitusional."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah pergerakan nasional, kebangkitan nasional tahun 1908 ditandai dengan berdirinya Boedi Oetomo. Apa makna historis paling penting dari kebangkitan nasional?",
                "opsi_a" => "Mulainya kesadaran kolektif bangsa Indonesia untuk memperjuangkan kemerdekaan",
                "opsi_b" => "Berakhirnya penjajahan Belanda di Indonesia",
                "opsi_c" => "Pembentukan pemerintahan Indonesia pertama",
                "opsi_d" => "Pengakuan kedaulatan Indonesia oleh dunia internasional",
                "opsi_e" => "Dimulainya revolusi industri di Indonesia",
                "jawaban_benar" => "A",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban A benar karena 1908 menandai kesadaran bangsa Indonesia untuk bersatu memperjuangkan kemerdekaan melalui organisasi modern. Opsi B terjadi 1945. Opsi C, D, dan E tidak sesuai konteks."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks Pancasila sebagai ideologi negara, sila pertama 'Ketuhanan Yang Maha Esa' memiliki implikasi penting. Manakah implikasi paling fundamental dari sila ini?",
                "opsi_a" => "Indonesia adalah negara agama tertentu",
                "opsi_b" => "Indonesia menganut sistem kerohanian yang menghargai keberagaman agama dan keyakinan",
                "opsi_c" => "Setiap warga negara harus menganut agama yang sama",
                "opsi_d" => "Negara tidak mengakui adanya agama",
                "opsi_e" => "Indonesia menganut sistem ateisme",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena sila pertama menegaskan kerohanian bangsa Indonesia dengan menghargai keberagaman agama dan keyakinan, bukan negara agama tertentu. Opsi A, C, D, dan E bertentangan dengan Pancasila."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah perjuangan Indonesia, Peristiwa Agresi Militer Belanda I (1947) memiliki karakteristik khusus. Manakah ciri paling menonjol dari agresi ini?",
                "opsi_a" => "Belanda mengakui kedaulatan Indonesia tanpa syarat",
                "opsi_b" => "Belanda melancarkan serangan militer untuk menguasai wilayah strategis Indonesia",
                "opsi_c" => "Indonesia dan Belanda melakukan perundingan damai",
                "opsi_d" => "Jepang membantu Indonesia melawan Belanda",
                "opsi_e" => "PBB mendukung Indonesia sepenuhnya",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Agresi Militer Belanda I (21 Juli 1947) adalah serangan militer Belanda untuk merebut kembali wilayah Indonesia dengan operasi Product. Opsi A, C, D, dan E tidak sesuai fakta sejarah."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks ketatanegaraan, sifat UUD 1945 mengalami perubahan seiring amandemen. Manakah perubahan paling signifikan dalam sifat UUD 1945 setelah amandemen?",
                "opsi_a" => "UUD 1945 menjadi lebih fleksibel dengan penambahan lembaga-lembaga baru dan pemilihan langsung",
                "opsi_b" => "UUD 1945 menjadi lebih kaku dan tidak bisa diubah",
                "opsi_c" => "UUD 1945 dihapuskan dan diganti dengan konstitusi baru",
                "opsi_d" => "UUD 1945 tidak lagi menjadi hukum dasar negara",
                "opsi_e" => "UUD 1945 hanya berlaku untuk kelompok tertentu",
                "jawaban_benar" => "A",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban A benar karena amandemen UUD 1945 menambahkan lembaga baru (MD, MK, KY), pemilihan langsung Presiden, dan pembatasan kekuasaan untuk mencegah kediktatoran. Opsi B, C, D, dan E salah konstitusional."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah Indonesia, peristiwa peristiwa 27 Juli 1996 memiliki makna politik tertentu. Apa konteks utama dari peristiwa ini?",
                "opsi_a" => "Kudeta militer terhadap pemerintahan",
                "opsi_b" => "Perebutan kekuasaan dalam internal Partai Demokrasi Indonesia",
                "opsi_c" => "Revolusi sosial yang menggulingkan rezim",
                "opsi_d" => "Pemilu bebas pertama setelah kemerdekaan",
                "opsi_e" => "Perjanjian perdamaian dengan Belanda",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena peristiwa 27 Juli 1996 terjadi dalam konteks dualisme kepemimpinan PDI antara Megawati Soekarnoputri (di-dukung massa) dan Soerjadi (diakui pemerintah). Opsi A, C, D, dan E tidak sesuai konteks."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sistem pemerintahan Indonesia, BPK (Badan Pemeriksa Keuangan) memiliki peran penting. Manakah fungsi paling utama BPK dalam sistem ketatanegaraan?",
                "opsi_a" => "Membentuk undang-undang negara",
                "opsi_b" => "Menguji undang-undang terhadap UUD 1945",
                "opsi_c" => "Memeriksa pengelolaan dan tanggung jawab keuangan negara",
                "opsi_d" => "Menjalankan pemerintahan sehari-hari",
                "opsi_e" => "Memimpin militer negara",
                "jawaban_benar" => "C",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban C benar karena BPK adalah lembaga negara yang memiliki wewenang memeriksa pengelolaan dan tanggung jawab keuangan negara (Pasal 23E UUD 1945). Opsi A adalah fungsi DPR, B adalah MK, D adalah eksekutif, E adalah TNI/Polri."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah Indonesia, Kebangkitan Nasional Indonesia tahun 1908 tidak terlepas dari peran tokoh tertentu. Siapa tokoh utama pendiri Boedi Oetomo?",
                "opsi_a" => "Ir. Soekarno dan Drs. Moh. Hatta",
                "opsi_b" => "Dr. Wahidin Soedirohoesodo dan Dr. Soetomo",
                "opsi_c" => "Tan Malaka dan Semaun",
                "opsi_d" => "Tjokroaminoto dan Agus Salim",
                "opsi_e" => "Kartini dan Dewi Sartika",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Boedi Oetomo didirikan oleh Dr. Wahidin Soedirohoesodo dan dr. Soetomo di STOVIA pada 20 Mei 1908. Opsi A adalah pendiri negara. Opsi C adalah tokoh komunis. Opsi D adalah tokoh SI. Opsi E adalah tokoh perempuan."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sistem ketatanegaraan Indonesia, Komisi Yudisial (KY) adalah lembaga negara yang dibentuk setelah amandemen UUD 1945. Manakah fungsi utama Komisi Yudisial?",
                "opsi_a" => "Membentuk undang-undang dan mengawasi pemerintah",
                "opsi_b" => "Mengusulkan calon hakim agung kepada DPR dan mengawasi perilaku hakim",
                "opsi_c" => "Menjalankan pemerintahan sebagai eksekutif",
                "opsi_d" => "Memutuskan sengketa antara negara dan warga negara",
                "opsi_e" => "Memimpin mahkamah agung sebagai ketua",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Komisi Yudisial berwenang mengusulkan calon hakim agung kepada DPR dan mengawasi perilaku hakim untuk menjaga independensi peradilan. Opsi A adalah DPR, C adalah eksekutif, D adalah pengadilan, E tidak sesuai."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah Indonesia, Peristiwa Madiun 1948 memiliki konteks historis tertentu. Apa latar belakang utama peristiwa ini?",
                "opsi_a" => "Pemberontakan komunis di bawah pimpinan Musso dan Amir Syarifuddin",
                "opsi_b" => "Agresi militer Belanda terhadap Indonesia",
                "opsi_c" => "Pemilu pertama Republik Indonesia",
                "opsi_d" => "Perundingan antara Indonesia dan Belanda",
                "opsi_e" => "Serbuan militer Sekutu ke Indonesia",
                "jawaban_benar" => "A",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban A benar karena Peristiwa Madiun 1948 adalah pemberontakan komunis di bawah Musso dan Amir Syarifuddin yang ingin menjadikan Indonesia negara komunis. Opsi B adalah Agresi Militer Belanda II. Opsi C, D, dan E tidak sesuai konteks."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks Pancasila sebagai dasar negara, sila keempat 'Kerakyatan yang dipimpin oleh hikmat kebijaksanaan dalam permusyawaratan/perwakilan' memiliki makna filosofis. Apa esensi dari sila ini?",
                "opsi_a" => "Sistem monarki dengan raja sebagai pemimpin tertinggi",
                "opsi_b" => "Demokrasi yang tidak terbatas tanpa aturan",
                "opsi_c" => "Sistem demokrasi berdasarkan kebijaksanaan dengan permusyawaratan untuk mencapai mufakat",
                "opsi_d" => "Otoritarianisme dengan kekuasaan absolut",
                "opsi_e" => "Anarkisme tanpa pemerintahan",
                "jawaban_benar" => "C",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban C benar karena sila keempat menegaskan sistem demokrasi Pancasila yang dipimpin oleh kebijaksanaan dalam permusyawaratan untuk mufakat, bukan demokrasi liberal atau otoritarian. Opsi A, B, D, dan E tidak sesuai dengan nilai Pancasila."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah Indonesia, peristiwa Konfrontasi Indonesia-Malaysia 1963-1966 memiliki latar belakang politik. Apa alasan utama Indonesia menentang pembentukan Malaysia?",
                "opsi_a" => "Indonesia ingin menguasai wilayah Malaysia",
                "opsi_b" => "Indonesia menilai Malaysia sebagai bentuk neo-kolonialisme Inggris di Asia Tenggara",
                "opsi_c" => "Indonesia tidak suka dengan budaya Malaysia",
                "opsi_d" => "Indonesia ingin memisahkan Singapura dari Malaysia",
                "opsi_e" => "Indonesia ingin membentuk uni dengan Malaysia",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Indonesia dipimpin Soekarno menentang Malaysia sebagai bentuk neo-kolonialisme dan neo-imperialisme Inggris di Asia Tenggara. Opsi A, C, D, dan E tidak sesuai dengan alasan politik Konfrontasi."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sistem ketatanegaraan, Mahkamah Agung memiliki kedudukan tertentu dalam struktur peradilan. Apa fungsi utama Mahkamah Agung?",
                "opsi_a" => "Membentuk undang-undang dan mengawasi pemerintah",
                "opsi_b" => "Menguji undang-undang terhadap UUD 1945",
                "opsi_c" => "Memeriksa dan mengadili perkara perdata dan pidana sebagai pengadilan terakhir",
                "opsi_d" => "Menjalankan pemerintahan sebagai eksekutif",
                "opsi_e" => "Melantik Presiden dan Wakil Presiden",
                "jawaban_benar" => "C",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban C benar karena Mahkamah Agung adalah pengadilan tertinggi yang memeriksa dan mengadili perkara perdata, pidana, dan militer sebagai pengadilan terakhir (kassasi). Opsi A adalah DPR, B adalah MK, D adalah eksekutif, E adalah MPR."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah Indonesia, peristiwa Supersemar 1966 memiliki dampak politik fundamental. Apa implikasi paling signifikan dari peristiwa ini?",
                "opsi_a" => "Pengukuhan kekuasaan Presiden Soekarno tanpa batas",
                "opsi_b" => "Transfer kekuasaan dari Soekarno ke Soeharto dan pembubaran PKI",
                "opsi_c" => "Pemilu demokratis pertama di Indonesia",
                "opsi_d" => "Pengakuan kemerdekaan Indonesia oleh dunia",
                "opsi_e" => "Pembentukan negara federal Indonesia",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Surat Perintah 11 Maret 1966 (Supersemar) menandai transfer kekuasaan dari Soekarno ke Soeharto dan pembubaran PKI, menandai dimulainya Orde Baru. Opsi A, C, D, dan E tidak sesuai fakta sejarah."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks sejarah Indonesia, Perjanjian Linggarjati 1946 memiliki makna diplomatik penting. Apa hasil utama dari perjanjian ini?",
                "opsi_a" => "Pengakuan penuh kemerdekaan Indonesia oleh Belanda",
                "opsi_b" => "Pengakuan wilayah Republik Indonesia terbatas di Jawa, Madura, dan Sumatera",
                "opsi_c" => "Pembentukan negara federal Indonesia yang permanen",
                "opsi_d" => "Penarikan seluruh pasukan Belanda dari Indonesia",
                "opsi_e" => "Pengakuan Indonesia sebagai anggota PBB",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Perjanjian Linggarjati (15 November 1946) mengakui Republik Indonesia di wilayah Jawa, Madura, dan Sumatera, dengan pembentukan negara federal di luar wilayah tersebut. Opsi A salah karena pengakuan terbatas. Opsi C, D, dan E tidak sesuai."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sistem ketatanegaraan Indonesia, DPR (Dewan Perwakilan Rakyat) memiliki fungsi legislatif dan pengawasan. Manakah fungsi paling fundamental DPR dalam sistem presidensial Indonesia?",
                "opsi_a" => "Memilih dan melantik Presiden dan Wakil Presiden",
                "opsi_b" => "Membentuk undang-undang bersama Presiden dan mengawasi pemerintahan",
                "opsi_c" => "Menguji undang-undang terhadap UUD 1945",
                "opsi_d" => "Memeriksa pengelolaan keuangan negara",
                "opsi_e" => "Menjalankan pemerintahan sebagai eksekutif",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena DPR memiliki fungsi legislasi (membentuk UU bersama Presiden) dan fungsi anggaran serta pengawasan terhadap pemerintahan. Opsi A adalah MPR, C adalah MK, D adalah BPK, E adalah eksekutif."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah pergerakan nasional, tokoh Mohammad Hatta memiliki peran penting selain sebagai proklamator. Apa kontribusi Mohammad Hatta yang paling fundamental bagi Indonesia?",
                "opsi_a" => "Memimpin militer dalam perang melawan Belanda",
                "opsi_b" => "Mengembangkan sistem ekonomi terpimpin dan federalisme yang berkembang menjadi ekonomi kerakyatan",
                "opsi_c" => "Mendirikan partai politik pertama di Indonesia",
                "opsi_d" => "Menjadi raja pertama Indonesia",
                "opsi_e" => "Memimpin organisasi perempuan nasional",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Mohammad Hatta adalah Bapak Koperasi Indonesia yang mengembangkan sistem ekonomi kerakyatan melalui koperasi. Opsi A salah karena Hatta bukan militer. Opsi C adalah tokoh SI. Opsi D dan E tidak sesuai."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks geopolitik, Indonesia adalah negara kepulauan terbesar di dunia. Manakah implikasi geopolitik paling signifikan dari status ini?",
                "opsi_a" => "Indonesia memiliki batas darat dengan banyak negara",
                "opsi_b" => "Indonesia memiliki wilayah laut dan udara yang sangat luas yang memerlukan pengelolaan pertahanan dan ekonomi maritim",
                "opsi_c" => "Indonesia terletak di benua tunggal tanpa pulau-pulau",
                "opsi_d" => "Indonesia tidak memiliki sumber daya laut",
                "opsi_e" => "Indonesia tidak memiliki perbatasan internasional",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena sebagai negara kepulauan terbesar, Indonesia memiliki wilayah laut dan udara yang sangat luas yang menjadi tanggung jawab pertahanan dan sumber ekonomi maritim. Opsi A, C, D, dan E salah secara geografis."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah Indonesia, peristiwa Timor Timur memilih merdeka dalam referendum 1999 memiliki konteks historis. Apa latar belakang referendum ini?",
                "opsi_a" => "Tekanan internasional setelah krisis kemanusiaan dan jatuhnya rezim Soeharto",
                "opsi_b" => "Keinginan Indonesia untuk memperluas wilayah",
                "opsi_c" => "Permintaan dari negara-negara tetangga ASEAN",
                "opsi_d" => "Perang saudara antara kelompok pro-Indonesia dan pro-kemerdekaan",
                "opsi_e" => "Kolaborasi Indonesia dengan Portugal tanpa konflik",
                "jawaban_benar" => "A",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban A benar karena referendum 1999 terjadi setelah krisis kemanusiaan, jatuhnya Orde Baru, dan tekanan internasional. Hasilnya mayoritas memilih merdeka. Opsi B, C, D, dan E tidak sesuai fakta sejarah."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks Pancasila, sila kelima 'Keadilan sosial bagi seluruh rakyat Indonesia' memiliki implikasi ekonomi. Apa makna paling fundamental dari sila ini?",
                "opsi_a" => "Sistem ekonomi liberal tanpa campur tangan negara",
                "opsi_b" => "Sistem ekonomi dengan pemerataan kesempatan, kesejahteraan, dan keadilan sosial",
                "opsi_c" => "Sistem ekonomi komunis dengan semua milik negara",
                "opsi_d" => "Sistem ekonomi feudal dengan pemilik tanah absolut",
                "opsi_e" => "Sistem ekonomi diskriminatif berdasarkan kelas sosial",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena sila kelima menegaskan ekonomi Pancasila dengan keadilan sosial, pemerataan kesempatan, dan kesejahteraan seluruh rakyat. Opsi A adalah liberalisme, C adalah komunisme, D dan E tidak sesuai dengan nilai Pancasila."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah pergerakan nasional, tokoh Kartini memiliki peran penting dalam emansipasi perempuan. Apa kontribusi paling fundamental Kartini?",
                "opsi_a" => "Memimpin perang melawan Belanda",
                "opsi_b" => "Memperjuangkan pendidikan dan emansipasi perempuan Indonesia melalui tulisan dan pemikiran",
                "opsi_c" => "Mendirikan partai politik perempuan pertama",
                "opsi_d" => "Menjadi presiden wanita pertama Indonesia",
                "opsi_e" => "Memimpin revolusi sosial di Jawa",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Kartini adalah pelopor emansipasi perempuan Indonesia yang memperjuangkan pendidikan dan kesetaraan melalui surat-menyurat dan pemikirannya. Opsi A, C, D, dan E tidak sesuai dengan peran Kartini."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sistem ketatanegaraan, Dewan Perwakilan Daerah (DPD) memiliki fungsi khusus dibandingkan DPR. Manakah fungsi utama DPD?",
                "opsi_a" => "Membentuk undang-undang bersama DPR dan Presiden",
                "opsi_b" => "Mengusulkan RUU yang terkait dengan otonomi daerah dan sumber daya alam, serta memperjuangkan aspirasi daerah",
                "opsi_c" => "Menguji undang-undang terhadap UUD 1945",
                "opsi_d" => "Menjalankan pemerintahan sebagai eksekutif daerah",
                "opsi_e" => "Memimpin daerah sebagai gubernur",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena DPD berfungsi mengusulkan RUU terkait otonomi daerah, sumber daya alam, dan memperjuangkan aspirasi daerah (Pasal 22D UUD 1945). Opsi A adalah DPR, C adalah MK, D dan E tidak sesuai."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah Indonesia, peristiwa Gerakan 30 September 1965 (G30S) memiliki dampak jangka panjang terhadap politik Indonesia. Apa dampak paling fundamental?",
                "opsi_a" => "Penguatan ideologi komunis di Indonesia",
                "opsi_b" => "Pergeseran politik luar negeri Indonesia dari blok Timur ke Barat dan pemberantasan PKI",
                "opsi_c" => "Pemilu bebas pertama di Indonesia",
                "opsi_d" => "Pengakuan kedaulatan Indonesia oleh PBB",
                "opsi_e" => "Pembentukan ASEAN oleh Indonesia",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena G30S mengakibatkan perubahan orientasi politik Indonesia dari pro-komunis menjadi anti-komunis, bergabung dengan blok Barat, dan pemberantasan PKI. Opsi A salah karena komunis diberantas. Opsi C, D, dan E tidak sesuai konteks."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks sejarah, peristiwa Perundingan Roem-Van Roijen 1949 memiliki makna diplomatik. Apa hasil utama dari perundingan ini?",
                "opsi_a" => "Pengakuan penuh kemerdekaan Indonesia oleh Belanda tanpa syarat",
                "opsi_b" => "Gencatan senjata, pembebasan tahanan politik, dan persiapan Konferensi Meja Bundar",
                "opsi_c" => "Pembentukan negara federal Indonesia yang permanen",
                "opsi_d" => "Pembagian wilayah Indonesia menjadi dua negara berdaulat",
                "opsi_e" => "Penyerahan kedaulatan dari Jepang ke Indonesia",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Perundingan Roem-Van Roijen (7 Mei 1949) menghasilkan gencatan senjata, pembebasan tahanan politik, dan persiapan KMB. Opsi A adalah hasil KMB. Opsi C, D, dan E tidak sesuai."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sistem ketatanegaraan Indonesia, Presiden sebagai kepala negara dan kepala pemerintahan memiliki wewenang tertentu. Manakah wewenang yang paling fundamental?",
                "opsi_a" => "Membentuk undang-undang tanpa persetujuan DPR",
                "opsi_b" => "Menjalankan pemerintahan dan menetapkan kebijakan pemerintahan sesuai UUD 1945",
                "opsi_c" => "Mengubah UUD 1945 sendirian",
                "opsi_d" => "Memutuskan perkara perdata dan pidana",
                "opsi_e" => "Memeriksa pengelolaan keuangan negara",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Presiden adalah pemegang kekuasaan eksekutif yang menjalankan pemerintahan dan menetapkan kebijakan sesuai UUD 1945. Opsi A salah karena UU perlu persetujuan DPR. Opsi C adalah MPR. Opsi D adalah pengadilan. Opsi E adalah BPK."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah Indonesia, peristiwa Desentralisasi 1903 (Decentralisatie Wet) memiliki makna administratif. Apa dampak utama dari kebijakan ini?",
                "opsi_a" => "Pembentukan pemerintahan Indonesia yang merdeka",
                "opsi_b" => "Pemberian kewenangan terbatas kepada pemerintah daerah Hindia Belanda dalam urusan dalam negeri",
                "opsi_c" => "Penghapusan seluruh pemerintahan tradisional di Indonesia",
                "opsi_d" => "Pengakuan kemerdekaan Indonesia oleh Belanda",
                "opsi_e" => "Pemindahan ibu kota Belanda ke Indonesia",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Desentralisatie Wet 1903 memberikan kewenangan terbatas kepada pemerintah daerah dalam urusan dalam negeri seperti pendidikan dan kesehatan, tetapi tetap di bawah kontrol pusat. Opsi A, C, D, dan E tidak sesuai."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks sejarah pergerakan nasional, organisasi Jong Java memiliki karakteristik tertentu. Apa ciri khas utama Jong Java?",
                "opsi_a" => "Organisasi politik yang menuntut kemerdekaan segera",
                "opsi_b" => "Organisasi kepemudaan yang memajukan budaya dan kepentingan Jawa dalam batasan loyalitas kolonial",
                "opsi_c" => "Organisasi militer yang melawan Belanda",
                "opsi_d" => "Organisasi agama yang menyebarluaskan Islam",
                "opsi_e" => "Organisasi perdagangan yang memonopoli ekonomi",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Jong Java (1918) adalah organisasi kepemudaan yang memajukan budaya Jawa, pendidikan, dan kepentingan etnis Jawa tetapi masih dalam batasan loyalitas pada pemerintah kolonial. Opsi A, C, D, dan E tidak sesuai."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sistem ketatanegaraan, Dewan Pertimbangan Presiden (Wantimpres) memiliki fungsi khusus. Apa fungsi utama Wantimpres?",
                "opsi_a" => "Membentuk undang-undang dan mengawasi pemerintah",
                "opsi_b" => "Memberikan pertimbangan dan nasihat kepada Presiden dalam menjalankan pemerintahan",
                "opsi_c" => "Menguji undang-undang terhadap UUD 1945",
                "opsi_d" => "Memeriksa pengelolaan keuangan negara",
                "opsi_e" => "Memimpin militer sebagai panglima tertinggi",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Wantimpres adalah lembaga yang memberikan pertimbangan dan nasihat kepada Presiden dalam menjalankan pemerintahan (Pasal 16 UUD 1945). Opsi A adalah DPR, C adalah MK, D adalah BPK, E adalah Presiden."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah Indonesia, peristiwa Reformasi 1998 memiliki ciri khas dibandingkan perubahan rezim sebelumnya. Apa ciri khas paling menonjol dari Reformasi 1998?",
                "opsi_a" => "Pergantian kekuasaan melalui revolusi bersenjata",
                "opsi_b" => "Perubahan sistem politik dari otoritarianisme menuju demokrasi dengan amandemen UUD 1945",
                "opsi_c" => "Pemindahan ibu kota negara",
                "opsi_d" => "Pembentukan negara federal",
                "opsi_e" => "Pengakuan kedaulatan oleh negara kolonial",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Reformasi 1998 mengakhiri Orde Baru, membawa perubahan sistem politik dari otoritarianisme ke demokrasi dengan amandemen UUD 1945. Opsi A salah karena bukan revolusi bersenjata. Opsi C, D, dan E tidak sesuai."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sistem ketatanegaraan Indonesia, Ombudsman Republik Indonesia memiliki fungsi pengawasan. Apa fungsi utama Ombudsman?",
                "opsi_a" => "Membentuk undang-undang baru",
                "opsi_b" => "Mengawasi penyelenggaraan negara dan memberikan rekomendasi perbaikan pelayanan publik",
                "opsi_c" => "Menguji undang-undang terhadap UUD 1945",
                "opsi_d" => "Menjalankan pemerintahan sebagai eksekutif",
                "opsi_e" => "Memimpin lembaga peradilan",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Ombudsman mengawasi penyelenggaraan negara terutama pelayanan publik dan memberikan rekomendasi perbaikan. Opsi A adalah DPR, C adalah MK, D adalah eksekutif, E adalah pengadilan."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah pergerakan nasional, organisasi Jong Islamieten Bond (JIB) memiliki karakteristik keagamaan. Apa fokus utama organisasi ini?",
                "opsi_a" => "Perjuangan kemerdekaan dengan kekerasan bersenjata",
                "opsi_b" => "Pemajuan kepentingan agama Islam dan kebangsaan dalam batasan moderat",
                "opsi_c" => "Pembaruan pendidikan Barat tanpa unsur agama",
                "opsi_d" => "Pembentukan negara komunis di Indonesia",
                "opsi_e" => "Pemisahan agama dari negara",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena JIB (1925) adalah organisasi pemuda Islam yang memajukan kepentingan agama Islam dan kebangsaan dengan pendekatan moderat. Opsi A, C, D, dan E tidak sesuai dengan karakter JIB."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks sejarah, pembubaran PKI tahun 1966 memiliki implikasi politik. Apa dampak langsung dari pembubaran PKI?",
                "opsi_a" => "PKI menjadi partai politik terbesar di Indonesia",
                "opsi_b" => "Berakhirnya pengaruh komunis di Indonesia dan perubahan orientasi politik luar negeri",
                "opsi_c" => "Penguatan blok Timur di Indonesia",
                "opsi_d" => "Terbentuknya aliansi militer dengan Uni Soviet",
                "opsi_e" => "Pemilihan umum langsung untuk pertama kali",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena pembubaran PKI mengakhiri pengaruh komunis di Indonesia dan mengubah orientasi politik dari pro-blok Timur ke Barat. Opsi A, C, D, dan E tidak sesuai fakta sejarah."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sistem ketatanegaraan, DPRD (Dewan Perwakilan Rakyat Daerah) memiliki fungsi di tingkat daerah. Manakah fungsi paling fundamental DPRD?",
                "opsi_a" => "Membentuk peraturan daerah bersama kepala daerah dan mengawasi pemerintahan daerah",
                "opsi_b" => "Menguji peraturan daerah terhadap UUD 1945",
                "opsi_c" => "Memeriksa pengelolaan keuangan negara secara nasional",
                "opsi_d" => "Menjalankan pemerintahan sebagai eksekutif nasional",
                "opsi_e" => "Melantik Presiden dan Wakil Presiden",
                "jawaban_benar" => "A",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban A benar karena DPRD berfungsi membentuk peraturan daerah bersama kepala daerah dan mengawasi pemerintahan daerah. Opsi B adalah pengadilan, C adalah BPK, D adalah eksekutif nasional, E adalah MPR."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah Indonesia, peristiwa Blitar 1926 memiliki konteks historis tertentu. Apa peristiwa yang terjadi di Blitar tahun 1926?",
                "opsi_a" => "Pemberontakan komunis di bawah pimpinan Semaun dan Alimin yang menjadi pemicu pembubaran PKI",
                "opsi_b" => "Agresi militer Belanda terhadap Indonesia",
                "opsi_c" => "Perundingan kemerdekaan antara Indonesia dan Belanda",
                "opsi_d" => "Pemilu pertama Republik Indonesia",
                "opsi_e" => "Pembentukan organisasi pemuda nasional",
                "jawaban_benar" => "A",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban A benar karena Pemberontakan Blitar 1926 adalah bagian dari pemberontakan komunis di Java yang dipimpin Semaun dan Alimen, menjadi pemicu pembubaran PKI pertama. Opsi B, C, D, dan E tidak sesuai konteks."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks Pancasila, sila kedua 'Kemanusiaan yang adil dan beradab' memiliki implikasi hukum. Apa makna paling fundamental dari sila ini?",
                "opsi_a" => "Sistem hukum yang diskriminatif berdasarkan status sosial",
                "opsi_b" => "Penghargaan terhadap harkat dan martabat manusia serta perlindungan hak asasi manusia",
                "opsi_c" => "Sistem hukum yang membedakan hak berdasarkan agama",
                "opsi_d" => "Hukum yang hanya berlaku untuk kelompok tertentu",
                "opsi_e" => "Sistem hukum tanpa perlindungan individu",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena sila kedua menegaskan penghargaan terhadap harkat dan martabat manusia serta perlindungan Hak Asasi Manusia (HAM) tanpa diskriminasi. Opsi A, C, D, dan E bertentangan dengan nilai kemanusiaan."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sejarah Indonesia, peristiwa Malari (Malapetaka Lima Belas Januari) 1974 memiliki konteks politik. Apa latar belakang utama peristiwa ini?",
                "opsi_a" => "Pemberontakan komunis di Indonesia",
                "opsi_b" => "Protes terhadap dominasi ekonomi asing dan ketidakpuasan terhadap pemerintahan Orde Baru",
                "opsi_c" => "Perundingan kemerdekaan dengan Belanda",
                "opsi_d" => "Agresi militer Belanda terhadap Jakarta",
                "opsi_e" => "Pembentukan ASEAN oleh Indonesia",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena Peristiwa Malari 1974 adalah protes terhadap dominasi ekonomi asing (Jepang) dan ketidakpuasan terhadap politik Orde Baru. Opsi A adalah G30S/Madiun. Opsi C adalah perundingan 1945-1949. Opsi D adalah 1947/1948. Opsi E adalah 1967."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam sistem ketatanegaraan Indonesia, lembaga negara yang memiliki wewenang untuk memberhentikan Presiden dan/atau Wakil Presiden dari jabatannya adalah?",
                "opsi_a" => "Mahkamah Agung",
                "opsi_b" => "Dewan Perwakilan Rakyat",
                "opsi_c" => "Majelis Permusyawaratan Rakyat",
                "opsi_d" => "Mahkamah Konstitusi",
                "opsi_e" => "Komisi Yudisial",
                "jawaban_benar" => "C",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban C benar karena MPR adalah lembaga tertinggi negara yang berwenang melantik dan memberhentikan Presiden dan/atau Wakil Presiden dalam sidang MPR (Pasal 7 UUD 1945). Opsi A adalah pengadilan tertinggi, B adalah legislatif, D adalah penguji UU, E adalah pengawas hakim."
            ],
            [
                "kategori" => "TWK",
                "pertanyaan" => "Dalam konteks sejarah pergerakan nasional, tokoh Tjokroaminoto memiliki peran penting dalam perkembangan SI. Apa kontribusi paling fundamental Tjokroaminoto?",
                "opsi_a" => "Memimpin militer dalam perang melawan Belanda",
                "opsi_b" => "Memperjuangkan nasionalisme Indonesia dan memadukan semangat kebangsaan dengan keagamaan melalui Sarekat Islam",
                "opsi_c" => "Menjadi presiden pertama Indonesia",
                "opsi_d" => "Mendirikan partai komunis pertama di Indonesia",
                "opsi_e" => "Memimpin organisasi perempuan nasional",
                "jawaban_benar" => "B",
                "poin_a" => 0,
                "poin_b" => 0,
                "poin_c" => 0,
                "poin_d" => 0,
                "poin_e" => 0,
                "pembahasan" => "Jawaban B benar karena H.O.S. Tjokroaminoto adalah pemimpin Sarekat Islam yang memadukan nasionalisme dengan keagamaan, menjadikan SI organisasi terbesar pada masanya. Opsi A salah karena bukan militer. Opsi C adalah Soekarno. Opsi D adalah Semaun. Opsi E tidak sesuai."
            ]
        ];

        foreach ($questions as $question) {
            Soal::create($question);
        }

        $this->command->info('70 TWK HOTS questions seeded successfully!');
    }
}
